#include "build.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "compile.h"
#include "folders.h"
#include "sys.h"
#include "toolchain.h"

#ifndef PURR_VERSION
#define PURR_VERSION "0.0.0-dev"
#endif

// A growable argv for sys_run, ending with NULL.
typedef struct args {
    const char **items;
    int count;
    int cap;
} args;

static void arg(args *a, const char *s)
{
    if (a->count + 2 > a->cap) {
        a->cap = a->cap * 2 + 16;
        a->items = realloc(a->items, sizeof(char *) * (size_t)a->cap);
        if (!a->items) abort();
    }
    a->items[a->count++] = s;
    a->items[a->count] = NULL;
}

static void arg_list(args *a, const char *const *list)
{
    for (int i = 0; list[i]; i++) arg(a, list[i]);
}

static char *format(const char *fmt, const char *a, const char *b)
{
    const size_t n = strlen(fmt) + strlen(a) + (b ? strlen(b) : 0) + 1;
    char *out = malloc(n);
    if (!out) abort();
    snprintf(out, n, fmt, a, b ? b : "");
    return out;
}

// ---------------------------------------------------------------------------
// The game's files

typedef struct file_list {
    char **items;
    int count;
} file_list;

static void add_file(void *user, const char *path)
{
    file_list *list = user;
    list->items = realloc(list->items, sizeof(char *) * (size_t)(list->count + 1));
    if (!list->items) abort();
    const size_t n = strlen(path) + 1;
    list->items[list->count] = malloc(n);
    if (!list->items[list->count]) abort();
    memcpy(list->items[list->count++], path, n);
}

static file_list game_files(const char *folder)
{
    file_list list = {0};
    char *dir = path_join(folder, "");
    folder_find(dir, ".purr", add_file, &list);
    free(dir);
    return list;
}

// The folder's name, as a window title and a file name.
static const char *game_name(const char *folder)
{
    const char *name = path_base(folder);
    return name[0] ? name : "game";
}

// The generated host: the game in a window, through purr/run.h. The same as
// purr_add_game's (cmake/PurrLang.cmake).
static bool write_main(const char *path, const char *title, const bool stats)
{
    char escaped[512];
    size_t n = 0;
    for (const char *p = title; *p && n + 3 < sizeof escaped; p++) {
        if (*p == '"' || *p == '\\') escaped[n++] = '\\';
        escaped[n++] = *p;
    }
    escaped[n] = '\0';
    char text[1024];
    snprintf(text, sizeof text,
             "// Generated by purr. Do not edit.\n"
             "#include \"game.h\"\n"
             "#include \"purr/run.h\"\n"
             "\n"
             "int main(void)\n"
             "{\n"
             "    purr_run(&(purr_run_desc){.title = \"%s\", .stats = %s});\n"
             "}\n",
             escaped, stats ? "true" : "false");
    return sys_write_text(path, text);
}

// ---------------------------------------------------------------------------
// Compiler flags

// Determinism (see AGENTS.md): no fast-math and no contraction, in this order.
static const char *const common_flags[] = {"-std=c17", "-fno-fast-math", "-ffp-contract=off", "-w", NULL};
static const char *const debug_flags[] = {"-O0", "-g", NULL};
static const char *const release_flags[] = {"-O2", "-DNDEBUG", NULL};

#ifdef _WIN32
// The C runtime is linked statically, as in the prebuilt platform library, so
// players need no Visual C++ redistributable.
static const char *const native_flags[] = {"-fms-runtime-lib=static", "-D_CRT_SECURE_NO_WARNINGS", NULL};
static const char *const native_libs[] = {"-lopengl32", "-lglu32", "-lgdi32", "-lwinmm", "-luser32", "-lshell32",
                                          "-lkernel32", "-lole32", "-loleaut32", "-luuid", "-lcomdlg32",
                                          "-ladvapi32", "-lwinspool", NULL};
#define LIB_PREFIX ""
#define LIB_SUFFIX ".lib"
#define EXE_SUFFIX ".exe"
#else
static const char *const native_flags[] = {NULL};
static const char *const native_libs[] = {"-lm", "-lpthread", "-ldl", "-lrt", NULL};
#define LIB_PREFIX "lib"
#define LIB_SUFFIX ".a"
#define EXE_SUFFIX ""
#endif

// What the web platform library was built with (platform/, cmake/PurrFlags.cmake).
static const char *const web_link_flags[] = {"-sSINGLE_FILE=1", "-sEXIT_RUNTIME=1", "-sINITIAL_MEMORY=64MB",
                                             "-sALLOW_MEMORY_GROWTH=1", "-sSTACK_SIZE=1MB", "-sUSE_GLFW=3",
                                             "-sEXPORTED_RUNTIME_METHODS=ccall", "-sMIN_WEBGL_VERSION=2",
                                             "-sMAX_WEBGL_VERSION=2", NULL};

static void config_flags(args *a, const build_options *opts)
{
    arg_list(a, common_flags);
    arg_list(a, opts->release ? release_flags : debug_flags);
#ifdef _WIN32
    if (!opts->web && !opts->release) arg(a, "-gcodeview");
#endif
    if (!opts->web) arg_list(a, native_flags);
}

// One line with everything that decides the engine objects, so a change in
// any of it rebuilds them.
static char *stamp_of(const char *compiler, const build_options *opts)
{
    args a = {0};
    config_flags(&a, opts);
    size_t n = strlen(compiler) + strlen(PURR_VERSION) + 4;
    for (int i = 0; i < a.count; i++) n += strlen(a.items[i]) + 1;
    char *stamp = malloc(n);
    if (!stamp) abort();
    snprintf(stamp, n, "%s %s", PURR_VERSION, compiler);
    for (int i = 0; i < a.count; i++) {
        strcat(stamp, " ");
        strcat(stamp, a.items[i]);
    }
    free(a.items);
    return stamp;
}

static bool compile_c(const char *compiler, const build_options *opts, const char *source, const char *object,
                      const char *include, const char *gen)
{
    args a = {0};
    arg(&a, compiler);
    arg(&a, "-c");
    arg(&a, source);
    arg(&a, "-o");
    arg(&a, object);
    char *include_flag = format("-I%s", include, NULL);
    char *gen_flag = format("-I%s", gen, NULL);
    arg(&a, include_flag);
    arg(&a, gen_flag);
    config_flags(&a, opts);
    const int code = sys_run(a.items, NULL, false);
    free(include_flag);
    free(gen_flag);
    free(a.items);
    if (code == -1) fprintf(stderr, "purr: couldn't start %s\n", compiler);
    return code == 0;
}

// ---------------------------------------------------------------------------
// Engine objects, compiled once per configuration and kept

typedef struct engine_build {
    const char *compiler;
    const build_options *opts;
    const char *include;
    const char *gen;
    const char *out_dir;
    bool rebuild;
    bool ok;
    file_list objects;
} engine_build;

static void compile_engine_file(void *user, const char *source)
{
    engine_build *e = user;
    char name[512];
    snprintf(name, sizeof name, "%s.o", path_base(source));
    char *object = path_join(e->out_dir, name);
    if (e->ok && (e->rebuild || sys_mtime(object) < sys_mtime(source))) {
        e->ok = compile_c(e->compiler, e->opts, source, object, e->include, e->gen);
    }
    add_file(&e->objects, object);
    free(object);
}

// ---------------------------------------------------------------------------

static bool generate(const char *folder, const char *gen)
{
    file_list files = game_files(folder);
    if (files.count == 0) {
        fprintf(stderr, "purr: there are no .purr files in %s\n", folder);
        fprintf(stderr, "  = note: a game is every .purr file in its folder; add one, like game.purr\n");
        return false;
    }
    const codegen_options codegen = {"game", gen, true};
    return compile_program((const char **)files.items, files.count, &codegen, NULL);
}

char *purr_build(const char *root, const build_options *opts, const bool for_run)
{
    char *folder = path_absolute(opts->folder);
    const char *name = game_name(folder);
    char *include = path_join(root, "include");
    char *run_h = path_join(include, "purr/run.h");
    if (!sys_exists(run_h)) {
        fprintf(stderr, "purr: the engine files aren't next to purr, in %s\n", root);
        fprintf(stderr, "  = note: reinstall purr, or for a build of this repo run `cmake --install` first\n");
        return NULL;
    }

    char *compiler = opts->web ? find_emcc() : find_clang();
    if (!compiler) {
        if (opts->web) {
            fprintf(stderr, "purr: Emscripten isn't installed, and web builds need it\n");
            fprintf(stderr, "  = note: install emsdk (https://emscripten.org/docs/getting_started/downloads.html) "
                            "and set EMSDK to its folder\n");
        } else {
            fprintf(stderr, "purr: clang isn't installed, and purr needs it to build games\n");
            fprintf(stderr, "  = note: install LLVM (https://github.com/llvm/llvm-project/releases), add it to PATH, "
                            "or set LLVM_ROOT\n");
        }
        return NULL;
    }

    // Everything purr makes goes in <folder>/.purr/<configuration>.
    char *purr_dir = path_join(folder, ".purr");
    sys_mkdirs(purr_dir);
    char *ignore = path_join(purr_dir, ".gitignore");
    if (!sys_exists(ignore)) sys_write_text(ignore, "# Made by purr; safe to delete.\n*\n");
    char config[32];
    snprintf(config, sizeof config, "%s-%s", opts->web ? "web" : "native", opts->release ? "release" : "debug");
    char *cache = path_join(purr_dir, config);
    char *gen = path_join(cache, "gen");
    char *engine_dir = path_join(cache, "engine");
    sys_mkdirs(gen);
    sys_mkdirs(engine_dir);

    if (!generate(folder, gen)) return NULL;
    char *main_c = path_join(gen, "main.c");
    write_main(main_c, opts->title ? opts->title : name, opts->stats);

    // The engine: rebuilt when purr, the compiler or the flags change.
    char *stamp_path = path_join(engine_dir, "stamp");
    char *stamp = stamp_of(compiler, opts);
    char *old_stamp = sys_read_file(stamp_path, NULL);
    engine_build engine = {compiler, opts, include, gen, engine_dir, !old_stamp || strcmp(old_stamp, stamp) != 0, true,
                           {0}};
    char *engine_src = path_join(root, "src/engine/");
    folder_find(engine_src, ".c", compile_engine_file, &engine);
    if (!engine.ok) return NULL;
    sys_write_text(stamp_path, stamp);

    char *game_c = path_join(gen, "game.c");
    char *game_o = path_join(cache, "game.o");
    char *main_o = path_join(cache, "main.o");
    if (!compile_c(compiler, opts, game_c, game_o, include, gen)) return NULL;
    if (!compile_c(compiler, opts, main_c, main_o, include, gen)) return NULL;

    // Link.
    char *output;
    const char *suffix = opts->web ? ".html" : EXE_SUFFIX;
    if (opts->output && !for_run) {
        output = path_absolute(opts->output);
    } else {
        char file[512];
        snprintf(file, sizeof file, "%s%s", name, suffix);
        char *dir = for_run ? path_join(cache, "") : path_join(folder, "build");
        output = path_join(dir, file);
        free(dir);
    }
    char *output_dir = path_dir(output);
    sys_mkdirs(output_dir);

    args a = {0};
    arg(&a, compiler);
    arg(&a, game_o);
    arg(&a, main_o);
    for (int i = 0; i < engine.objects.count; i++) arg(&a, engine.objects.items[i]);
    // The prebuilt platform layer, raylib inside (see platform/CMakeLists.txt).
    char *lib_dir = path_join(root, opts->web ? "lib/web" : "lib/native");
    const char *lib_format = opts->web ? "%s/lib%s.a" : "%s/" LIB_PREFIX "%s" LIB_SUFFIX;
    char *platform_lib = format(lib_format, lib_dir, "purr_platform");
    char *raylib_lib = format(lib_format, lib_dir, "raylib");
    arg(&a, platform_lib);
    arg(&a, raylib_lib);
    arg(&a, "-o");
    arg(&a, output);
    arg_list(&a, opts->release ? release_flags : debug_flags);
    char *shell = NULL;
    if (opts->web) {
        shell = path_join(root, "web/shell.html");
        arg(&a, "--shell-file");
        arg(&a, shell);
        arg_list(&a, web_link_flags);
    } else {
        arg_list(&a, native_flags);
#ifdef _WIN32
        arg(&a, "-fuse-ld=lld");
        // A release game opens its window without a console next to it.
        if (opts->release) {
            arg(&a, "-Xlinker");
            arg(&a, "/subsystem:windows");
            arg(&a, "-Xlinker");
            arg(&a, "/entry:mainCRTStartup");
        }
#endif
        arg_list(&a, native_libs);
    }
    const int code = sys_run(a.items, NULL, false);
    free(a.items);
    if (code != 0) {
        if (code == -1) fprintf(stderr, "purr: couldn't start %s\n", compiler);
        return NULL;
    }
    return output;
}

bool purr_schedule(const char *folder_arg)
{
    char *folder = path_absolute(folder_arg);
    file_list files = game_files(folder);
    if (files.count == 0) {
        fprintf(stderr, "purr: there are no .purr files in %s\n", folder);
        return false;
    }
    const codegen_options codegen = {game_name(folder), NULL, true};
    sb text = {0};
    if (!compile_program((const char **)files.items, files.count, &codegen, &text)) return false;
    fputs(text.data, stdout);
    return true;
}
