#include "build.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "compile.h"
#include "folders.h"
#include "sys.h"
#include "toolchain.h"

#ifndef PURR_VERSION
#define PURR_VERSION "0.0.0-dev"
#endif

// A growable argv for sys_run, ending with NULL.
typedef struct args {
    const char **items;
    int count;
    int cap;
} args;

static void arg(args *a, const char *s)
{
    if (a->count + 2 > a->cap) {
        a->cap = a->cap * 2 + 16;
        a->items = realloc(a->items, sizeof(char *) * (size_t)a->cap);
        if (!a->items) abort();
    }
    a->items[a->count++] = s;
    a->items[a->count] = NULL;
}

static void arg_list(args *a, const char *const *list)
{
    for (int i = 0; list[i]; i++) arg(a, list[i]);
}

static char *format(const char *fmt, const char *a, const char *b)
{
    const size_t n = strlen(fmt) + strlen(a) + (b ? strlen(b) : 0) + 1;
    char *out = malloc(n);
    if (!out) abort();
    snprintf(out, n, fmt, a, b ? b : "");
    return out;
}

// ---------------------------------------------------------------------------
// The game's files

typedef struct file_list {
    char **items;
    int count;
} file_list;

static void add_file(void *user, const char *path)
{
    file_list *list = user;
    list->items = realloc(list->items, sizeof(char *) * (size_t)(list->count + 1));
    if (!list->items) abort();
    const size_t n = strlen(path) + 1;
    list->items[list->count] = malloc(n);
    if (!list->items[list->count]) abort();
    memcpy(list->items[list->count++], path, n);
}

static file_list game_files(const char *folder)
{
    file_list list = {0};
    char *dir = path_join(folder, "");
    folder_find(dir, ".purr", add_file, &list);
    free(dir);
    return list;
}

// The folder's name, as a window title and a file name.
static const char *game_name(const char *folder)
{
    const char *name = path_base(folder);
    return name[0] ? name : "game";
}

// The generated host: the game in a window, through purr/run.h. The same as
// purr_add_game's (cmake/PurrLang.cmake).
static bool write_main(const char *path, const char *title, const bool stats)
{
    char escaped[512];
    size_t n = 0;
    for (const char *p = title; *p && n + 3 < sizeof escaped; p++) {
        if (*p == '"' || *p == '\\') escaped[n++] = '\\';
        escaped[n++] = *p;
    }
    escaped[n] = '\0';
    char text[1024];
    snprintf(text, sizeof text,
             "// Generated by purr. Do not edit.\n"
             "#include \"game.h\"\n"
             "#include \"purr/run.h\"\n"
             "\n"
             "int main(void)\n"
             "{\n"
             "    purr_run(&(purr_run_desc){.title = \"%s\", .stats = %s});\n"
             "}\n",
             escaped, stats ? "true" : "false");
    return sys_write_text(path, text);
}

// ---------------------------------------------------------------------------
// Compiler flags

// Determinism (see AGENTS.md): no fast-math and no contraction, in this order.
static const char *const common_flags[] = {"-std=c17", "-fno-fast-math", "-ffp-contract=off", "-w", NULL};
static const char *const debug_flags[] = {"-O0", "-g", NULL};
static const char *const release_flags[] = {"-O2", "-DNDEBUG", NULL};

#ifdef _WIN32
// Windows games use the MinGW-w64 target, whose C runtime comes with purr (as
// in cmake/mingw-toolchain.cmake): Microsoft's can't be redistributed. Its C
// library is the UCRT, part of Windows, so games need no DLLs of their own.
#define NATIVE_TARGET "--target=x86_64-w64-windows-gnu"
#define NATIVE_RUNTIME "mingw"
static const char *const native_libs[] = {"-lmingw32", "-lmingwex", "-lmoldname", "-lmsvcrt", "-lkernel32",
                                          "-luser32", "-lgdi32", "-lshell32", "-ladvapi32", "-lopengl32",
                                          "-lwinmm", NULL};
#define EXE_SUFFIX ".exe"
#elif defined(__APPLE__)
// What raylib and its GLFW link on macOS.
static const char *const native_libs[] = {"-framework", "Cocoa", "-framework", "IOKit", "-framework", "CoreFoundation",
                                          "-framework", "CoreVideo", "-framework", "OpenGL", "-framework", "CoreAudio",
                                          "-framework", "AudioToolbox", NULL};
#define EXE_SUFFIX ""
#else
// raylib calls Xlib directly (the rest of X11 and OpenGL it loads at run time).
// The library itself, not -lX11: every desktop has it, but not every desktop
// has the development package that provides libX11.so.
static const char *const native_libs[] = {"-lm", "-lpthread", "-ldl", "-lrt", "-l:libX11.so.6", NULL};
#define EXE_SUFFIX ""
#endif

// Web builds: clang's own wasm target, with the package's wasi-libc (as in
// cmake/wasi-toolchain.cmake). The page's JavaScript implements the GL
// functions the platform imports, and allocates with malloc.
static const char *const web_link_flags[] = {"-Wl,--allow-undefined", "-Wl,--export=malloc", "-Wl,--export=free",
                                             "-Wl,-z,stack-size=1048576", NULL};

// The target, when it isn't the system's: its C library comes with purr, in
// <root>/<runtime>/sysroot, and its compiler runtime is passed by path, since
// clang looks for it in its own installation.
typedef struct target {
    const char *flag;   // --target=..., or NULL for the system's
    char *sysroot_flag; // --sysroot=...
    char *builtins;     // The compiler runtime
} target;

static target build_target;

static bool find_target(const char *root, const build_options *opts)
{
    const char *runtime = NULL;
    if (opts->web) {
        build_target.flag = "--target=wasm32-wasip1";
        runtime = "wasi";
    }
#ifdef NATIVE_TARGET
    else {
        build_target.flag = NATIVE_TARGET;
        runtime = NATIVE_RUNTIME;
    }
#endif
    if (!runtime) return true;
    char *dir = path_join(root, runtime);
    build_target.sysroot_flag = format("--sysroot=%s/sysroot", dir, NULL);
    build_target.builtins = opts->web ? path_join(dir, "libclang_rt.builtins.a")
                                      : path_join(dir, "libclang_rt.builtins-x86_64.a");
    const bool found = sys_exists(build_target.builtins);
    if (!found) {
        fprintf(stderr, "purr: this installation can't build %s games: %s is missing\n", opts->web ? "web" : "native",
                dir);
        fprintf(stderr, "  = note: reinstall purr, or for a build of this repo package the %s preset too\n",
                opts->web ? "web-package" : "mingw-release");
    }
    free(dir);
    return found;
}

static void config_flags(args *a, const build_options *opts)
{
    if (build_target.flag) {
        arg(a, build_target.flag);
        arg(a, build_target.sysroot_flag);
    }
    arg_list(a, common_flags);
    arg_list(a, opts->release ? release_flags : debug_flags);
#ifdef _WIN32
    // Debug info Visual Studio's debugger reads, in a .pdb next to the game.
    if (!opts->web && !opts->release) arg(a, "-gcodeview");
#endif
}

// The C compiler: an installed clang, or purr itself as `purr cc` when clang
// is built in (compiler/cli/llvm).
static void arg_compiler(args *a, const char *compiler)
{
    arg(a, compiler);
#ifdef PURR_EMBEDDED_CLANG
    arg(a, "cc");
#endif
}

// One line with everything that decides the engine objects, so a change in
// any of it rebuilds them.
static char *stamp_of(const char *compiler, const build_options *opts)
{
    args a = {0};
    config_flags(&a, opts);
    size_t n = strlen(compiler) + strlen(PURR_VERSION) + 4;
    for (int i = 0; i < a.count; i++) n += strlen(a.items[i]) + 1;
    char *stamp = malloc(n);
    if (!stamp) abort();
    snprintf(stamp, n, "%s %s", PURR_VERSION, compiler);
    for (int i = 0; i < a.count; i++) {
        strcat(stamp, " ");
        strcat(stamp, a.items[i]);
    }
    free(a.items);
    return stamp;
}

static bool compile_c(const char *compiler, const build_options *opts, const char *source, const char *object,
                      const char *include, const char *gen)
{
    args a = {0};
    arg_compiler(&a, compiler);
    arg(&a, "-c");
    arg(&a, source);
    arg(&a, "-o");
    arg(&a, object);
    char *include_flag = format("-I%s", include, NULL);
    char *gen_flag = format("-I%s", gen, NULL);
    arg(&a, include_flag);
    arg(&a, gen_flag);
    config_flags(&a, opts);
    const int code = sys_run(a.items, NULL, false);
    free(include_flag);
    free(gen_flag);
    free(a.items);
    if (code == -1) fprintf(stderr, "purr: couldn't start %s\n", compiler);
    return code == 0;
}

// ---------------------------------------------------------------------------
// Engine objects, compiled once per configuration and kept

typedef struct engine_build {
    const char *compiler;
    const build_options *opts;
    const char *include;
    const char *gen;
    const char *out_dir;
    bool rebuild;
    bool ok;
    file_list objects;
} engine_build;

static void compile_engine_file(void *user, const char *source)
{
    engine_build *e = user;
    char name[512];
    snprintf(name, sizeof name, "%s.o", path_base(source));
    char *object = path_join(e->out_dir, name);
    if (e->ok && (e->rebuild || sys_mtime(object) < sys_mtime(source))) {
        e->ok = compile_c(e->compiler, e->opts, source, object, e->include, e->gen);
    }
    add_file(&e->objects, object);
    free(object);
}

// ---------------------------------------------------------------------------
// The web page: the package's shell, with a <script> holding the program as
// base64 and purr.js, which runs it. The same as cmake/web_page.mjs.

static char *base64(const unsigned char *data, const size_t len)
{
    static const char digits[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    char *out = malloc((len + 2) / 3 * 4 + 1);
    if (!out) abort();
    size_t n = 0;
    for (size_t i = 0; i < len; i += 3) {
        const unsigned v = (unsigned)data[i] << 16 | (i + 1 < len ? (unsigned)data[i + 1] << 8 : 0)
                         | (i + 2 < len ? data[i + 2] : 0);
        out[n++] = digits[v >> 18 & 63];
        out[n++] = digits[v >> 12 & 63];
        out[n++] = i + 1 < len ? digits[v >> 6 & 63] : '=';
        out[n++] = i + 2 < len ? digits[v & 63] : '=';
    }
    out[n] = '\0';
    return out;
}

static bool make_page(const char *root, const char *program, const char *page)
{
    char *shell_path = path_join(root, "web/shell.html");
    char *script_path = path_join(root, "web/purr.js");
    char *shell = sys_read_file(shell_path, NULL);
    char *script = sys_read_file(script_path, NULL);
    size_t wasm_len = 0;
    char *wasm = sys_read_file(program, &wasm_len);
    const char *slot = shell ? strstr(shell, "{{{ SCRIPT }}}") : NULL;
    if (!script || !wasm || !slot) {
        fprintf(stderr, "purr: the web page's files are missing from %s/web; reinstall purr\n", root);
        return false;
    }
    char *encoded = base64((const unsigned char *)wasm, wasm_len);
    FILE *f = fopen(page, "wb");
    if (!f) {
        fprintf(stderr, "purr: can't write %s\n", page);
        return false;
    }
    fwrite(shell, 1, (size_t)(slot - shell), f);
    fprintf(f, "<script>\nconst PURR_PROGRAM = \"%s\";\n%s</script>", encoded, script);
    fputs(slot + strlen("{{{ SCRIPT }}}"), f);
    const bool ok = fclose(f) == 0;
    free(encoded);
    free(wasm);
    return ok;
}

// ---------------------------------------------------------------------------

static bool generate(const char *folder, const char *gen)
{
    file_list files = game_files(folder);
    if (files.count == 0) {
        fprintf(stderr, "purr: there are no .purr files in %s\n", folder);
        fprintf(stderr, "  = note: a game is every .purr file in its folder; add one, like game.purr\n");
        return false;
    }
    const codegen_options codegen = {"game", gen, true};
    return compile_program((const char **)files.items, files.count, &codegen, NULL);
}

char *purr_build(const char *root, const build_options *opts, const bool for_run)
{
    char *folder = path_absolute(opts->folder);
    const char *name = game_name(folder);
    char *include = path_join(root, "include");
    char *run_h = path_join(include, "purr/run.h");
    if (!sys_exists(run_h)) {
        fprintf(stderr, "purr: the engine files aren't next to purr, in %s\n", root);
        fprintf(stderr, "  = note: reinstall purr, or for a build of this repo run `cmake --install` first\n");
        return NULL;
    }

#ifdef PURR_EMBEDDED_CLANG
    char *bin = sys_exe_dir();
    char *compiler = path_join(bin, "purr" EXE_SUFFIX);
#ifdef __APPLE__
    // macOS's headers and libraries come with Apple's command line tools,
    // which clang finds through SDKROOT.
    if (!opts->web && !find_macos_sdk()) {
        fprintf(stderr, "purr: building for macOS needs Apple's command line tools\n");
        fprintf(stderr, "  = note: install them with `xcode-select --install`\n");
        return NULL;
    }
#endif
#else
    char *compiler = opts->web ? find_web_clang() : find_clang();
    if (!compiler) {
        fprintf(stderr, "purr: clang isn't installed, and purr needs it to build games\n");
        fprintf(stderr, "  = note: install LLVM (https://github.com/llvm/llvm-project/releases), add it to PATH, "
                        "or set LLVM_ROOT\n");
        return NULL;
    }
    char *wasm_ld = NULL;
    if (opts->web) {
        wasm_ld = find_wasm_ld(compiler);
        if (!wasm_ld) {
            fprintf(stderr, "purr: web builds need wasm-ld, the WebAssembly linker, and it isn't next to clang\n");
            fprintf(stderr, "  = note: LLVM's releases include it; on Linux install your distribution's lld, and on "
                            "macOS `brew install llvm lld`\n");
            return NULL;
        }
    }
#endif
    if (!find_target(root, opts)) return NULL;

    // Everything purr makes goes in <folder>/.purr/<configuration>, hidden
    // like .git.
    char *purr_dir = path_join(folder, ".purr");
    sys_mkdirs(purr_dir);
    sys_hide(purr_dir);
    char *ignore = path_join(purr_dir, ".gitignore");
    if (!sys_exists(ignore)) sys_write_text(ignore, "# Made by purr; safe to delete.\n*\n");
    char config[32];
    snprintf(config, sizeof config, "%s-%s", opts->web ? "web" : "native", opts->release ? "release" : "debug");
    char *cache = path_join(purr_dir, config);
    char *gen = path_join(cache, "gen");
    char *engine_dir = path_join(cache, "engine");
    sys_mkdirs(gen);
    sys_mkdirs(engine_dir);

    if (!generate(folder, gen)) return NULL;
    char *main_c = path_join(gen, "main.c");
    write_main(main_c, opts->title ? opts->title : name, opts->stats);

    // The engine: rebuilt when purr, the compiler or the flags change.
    char *stamp_path = path_join(engine_dir, "stamp");
    char *stamp = stamp_of(compiler, opts);
    char *old_stamp = sys_read_file(stamp_path, NULL);
    engine_build engine = {compiler, opts, include, gen, engine_dir, !old_stamp || strcmp(old_stamp, stamp) != 0, true,
                           {0}};
    char *engine_src = path_join(root, "src/engine/");
    folder_find(engine_src, ".c", compile_engine_file, &engine);
    if (!engine.ok) return NULL;
    sys_write_text(stamp_path, stamp);

    char *game_c = path_join(gen, "game.c");
    char *game_o = path_join(cache, "game.o");
    char *main_o = path_join(cache, "main.o");
    if (!compile_c(compiler, opts, game_c, game_o, include, gen)) return NULL;
    if (!compile_c(compiler, opts, main_c, main_o, include, gen)) return NULL;

    // Link.
    char *output;
    const char *suffix = opts->web ? ".html" : EXE_SUFFIX;
    if (opts->output && !for_run) {
        output = path_absolute(opts->output);
    } else {
        char file[512];
        snprintf(file, sizeof file, "%s%s", name, suffix);
        char *dir = for_run ? path_join(cache, "") : path_join(folder, "build");
        output = path_join(dir, file);
        free(dir);
    }
    char *output_dir = path_dir(output);
    sys_mkdirs(output_dir);
    // Web builds link a .wasm, which then goes inside the page.
    char *program = output;
    if (opts->web) {
        char file[512];
        snprintf(file, sizeof file, "%s.wasm", name);
        program = path_join(cache, file);
    }

    args a = {0};
    arg_compiler(&a, compiler);
    if (build_target.flag) {
        arg(&a, build_target.flag);
        arg(&a, build_target.sysroot_flag);
    }
    arg(&a, game_o);
    arg(&a, main_o);
    for (int i = 0; i < engine.objects.count; i++) arg(&a, engine.objects.items[i]);
    // The prebuilt platform layer, raylib inside (see platform/CMakeLists.txt).
    char *lib_dir = path_join(root, opts->web ? "lib/web" : "lib/native");
    char *platform_lib = format("%s/lib%s.a", lib_dir, "purr_platform");
    char *raylib_lib = format("%s/lib%s.a", lib_dir, "raylib");
    arg(&a, platform_lib);
    arg(&a, raylib_lib);
    arg(&a, "-o");
    arg(&a, program);
    arg_list(&a, opts->release ? release_flags : debug_flags);
    if (opts->web) {
        arg_list(&a, web_link_flags);
#ifndef PURR_EMBEDDED_CLANG
        arg(&a, format("-fuse-ld=%s", wasm_ld, NULL)); // It may be elsewhere than clang, as with Homebrew
#endif
    } else {
#if defined(PURR_EMBEDDED_CLANG) && !defined(_WIN32)
        arg(&a, "-fuse-ld=lld"); // The built-in linker
#endif
#ifdef _WIN32
        arg(&a, "-fuse-ld=lld");
        // A release game opens its window without a console next to it; a
        // debug game gets its debug info in a .pdb.
        arg(&a, opts->release ? "-Wl,--subsystem,windows" : "-Wl,--pdb=");
#endif
        arg_list(&a, native_libs);
    }
    // A target's C library, when it comes with purr: its libraries by name
    // (on the web, just the C library) and the compiler runtime by path.
    if (build_target.flag) {
        arg(&a, "-nodefaultlibs");
        if (opts->web) arg(&a, "-lc");
        arg(&a, build_target.builtins);
    }
    const int code = sys_run(a.items, NULL, false);
    free(a.items);
    if (code != 0) {
        if (code == -1) fprintf(stderr, "purr: couldn't start %s\n", compiler);
        return NULL;
    }
    if (opts->web && !make_page(root, program, output)) return NULL;
    return output;
}

bool purr_schedule(const char *folder_arg)
{
    char *folder = path_absolute(folder_arg);
    file_list files = game_files(folder);
    if (files.count == 0) {
        fprintf(stderr, "purr: there are no .purr files in %s\n", folder);
        return false;
    }
    const codegen_options codegen = {game_name(folder), NULL, true};
    sb text = {0};
    if (!compile_program((const char **)files.items, files.count, &codegen, &text)) return false;
    fputs(text.data, stdout);
    return true;
}
