#pragma once

#include <stdbool.h>
#include <stdint.h>

// Entity table: hands out entity handles and records where each entity's data lives.
//
// Temporary implementation written for the PurrLang v0 transpiler; the project owner
// takes it over later. Code generated by purrc depends on the functions below.
//
// The table lives inside the world: fixed capacity, no pointers, and zero-initialized
// memory is a valid empty table, so snapshots and rollback cover it with a plain copy.

// Must be the same for the engine and generated code; don't override per target.
#ifndef PURR_MAX_ENTITIES
#define PURR_MAX_ENTITIES 16384u
#endif

// Archetype of an entity that is alive but whose spawn hasn't been applied yet.
#define PURR_ARCHETYPE_NONE 0xFFFFFFFFu

// A zeroed handle is the null entity; it is never alive.
typedef struct purr_entity {
    uint32_t index;
    uint32_t generation;
} purr_entity;

typedef struct purr_location {
    uint32_t archetype;
    uint32_t row;
} purr_location;

typedef struct purr_entity_slot {
    uint32_t generation; // Odd while alive, even while free.
    uint32_t archetype;
    uint32_t row;
    uint32_t snaps;      // Times it jumped (entity.Snap()): views only blend it between ticks with the same count
} purr_entity_slot;

typedef struct purr_entities {
    uint32_t next_unused;                       // Slots at or above this were never used.
    uint32_t free_count;
    uint32_t free_list[PURR_MAX_ENTITIES];      // LIFO, so reuse order is deterministic.
    purr_entity_slot slots[PURR_MAX_ENTITIES];
} purr_entities;

// Returns the null entity when the table is full.
purr_entity purr_entity_create(purr_entities *t);

// Returns false if the entity wasn't alive.
bool purr_entity_destroy(purr_entities *t, purr_entity e);

bool purr_entity_alive(const purr_entities *t, purr_entity e);

void purr_entity_set_location(purr_entities *t, purr_entity e, purr_location loc);

// It jumped: views draw it as it is, not blended from the tick before.
void purr_entity_snap(purr_entities *t, purr_entity e);

// Its snap count, or 0 if it isn't alive.
uint32_t purr_entity_snaps(const purr_entities *t, purr_entity e);

// Archetype is PURR_ARCHETYPE_NONE for dead entities and for pending spawns.
purr_location purr_entity_location(const purr_entities *t, purr_entity e);

// For snapshots: copies what's in use, and clears what `to` used beyond it, so
// past the counts a table is all zeros. The hash covers what's in use.
void purr_entities_copy(purr_entities *to, const purr_entities *from);
uint64_t purr_entities_hash(uint64_t h, const purr_entities *t);

static inline bool purr_entity_is_null(const purr_entity e)
{
    return e.generation == 0;
}

static inline bool purr_entity_equal(const purr_entity a, const purr_entity b)
{
    return a.index == b.index && a.generation == b.generation;
}
