#include "codegen.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "types.h"

// Emits C for a checked program. Everything specific to the game is generated
// here: component structs, archetype storage, deferred structural changes,
// system and view bodies, dispatch loops, the tick and drawing. See docs/purrlang.md.

typedef struct transition {
    int from;
    int to;
} transition;

typedef struct gen {
    program *prog;
    const codegen_options *opts;
    sb h;
    sb c;
    const char **paths;    // Each source file, with forward slashes: for #line
    const char *from;      // The source files, for the "Generated by" comments
    const char *c_path;
    VEC(transition) moves;
    int indent;
    bool in_input; // Generating the input's constructor: fields live in purr_self.
    const decl *routine; // The method or function being generated: a mut method's fields are purr_self->
    int spawn_temps;     // Temporaries for hoisted spawns, numbered per function.
} gen;

// ---------------------------------------------------------------------------
// C names

// Identifiers that would clash with C keywords, macros or library names in
// generated code. User names that hit one of these get a trailing underscore.
static const char *c_reserved[] = {
    "auto", "break", "case", "char", "const", "continue", "default", "do", "double", "else", "enum",
    "extern", "float", "for", "goto", "if", "inline", "int", "long", "register", "restrict", "return",
    "short", "signed", "sizeof", "static", "struct", "switch", "typedef", "union", "unsigned", "void",
    "volatile", "while", "alignas", "alignof", "bool", "constexpr", "false", "nullptr", "static_assert",
    "thread_local", "true", "typeof", "typeof_unqual", "NULL", "EOF", "FILE", "errno", "assert",
    "offsetof", "stdin", "stdout", "stderr", "int8_t", "int16_t", "int32_t", "int64_t", "uint8_t",
    "uint16_t", "uint32_t", "uint64_t", "intptr_t", "uintptr_t", "size_t", "ptrdiff_t", "wchar_t",
    "abort", "memset", "printf", "fprintf", "main",
};

static bool is_c_reserved(const str name)
{
    if (name.len > 0 && name.ptr[0] == '_') return true;
    for (size_t i = 0; i < sizeof c_reserved / sizeof c_reserved[0]; i++) {
        if (str_eq_c(name, c_reserved[i])) return true;
    }
    return false;
}

static const char *mangle(const str name)
{
    char *out = arena_alloc((size_t)name.len + 2);
    memcpy(out, name.ptr, (size_t)name.len);
    if (is_c_reserved(name)) out[name.len] = '_';
    return out;
}

// A declaration's name in C: its namespace joined with underscores, then its
// name, so Combat.Health is Combat_Health. The checker rejects names that
// would collide.
static const char *decl_cname(const decl *d)
{
    const str ns = d->unit ? d->unit->ns : (str){"", 0};
    if (ns.len == 0) return mangle(d->name);
    sb b = {0};
    for (int i = 0; i < ns.len; i++) sb_putn(&b, ns.ptr[i] == '.' ? "_" : &ns.ptr[i], 1);
    sb_put(&b, "_");
    sb_putn(&b, d->name.ptr, (size_t)d->name.len);
    return b.data;
}

static const char *type_cname(const decl *d)
{
    return decl_cname(d);
}

static const char *field_cname(const field *f)
{
    return mangle(f->name);
}

// Locals and parameters also can't reuse a type's name: in C that would hide
// the typedef inside the function.
static const char *local_cname(const gen *g, const str name)
{
    bool clash = is_c_reserved(name) || str_eq_c(name, "purr_float3");
    for (int i = 0; i < g->prog->decls.count && !clash; i++) {
        const decl *d = g->prog->decls.items[i];
        if (d->kind != DECL_SYSTEM && str_eq_c(name, type_cname(d))) clash = true;
    }
    char *out = arena_alloc((size_t)name.len + 2);
    memcpy(out, name.ptr, (size_t)name.len);
    if (clash) out[name.len] = '_';
    return out;
}

static const char *c_type(const type t)
{
    if (t.kind == TY_COMPONENT || t.kind == TY_SINGLETON || t.kind == TY_INPUT || t.kind == TY_STRUCT) {
        return type_cname(t.decl);
    }
    if (t.kind == TY_RECORD) return t.decl->c_name;
    return type_c_name(t);
}

static const char *const xyzw[] = {"x", "y", "z", "w"};

static bool has_component(const uint64_t mask, const int component)
{
    return (mask >> component) & 1;
}

// "arch0_Transform_Player": the world member and, prefixed with purr_, the type.
static const char *arch_name(const gen *g, const int index)
{
    const uint64_t mask = g->prog->archetypes.items[index];
    sb b = {0};
    sb_printf(&b, "arch%d", index);
    if (mask == 0) sb_put(&b, "_empty");
    for (int i = 0; i < g->prog->components.count; i++) {
        if (has_component(mask, i)) sb_printf(&b, "_%s", type_cname(g->prog->components.items[i]));
    }
    return b.data;
}

// "Transform, Player" for comments and error messages.
static const char *arch_label(const gen *g, const int index)
{
    const uint64_t mask = g->prog->archetypes.items[index];
    sb b = {0};
    sb_put(&b, "");
    bool first = true;
    for (int i = 0; i < g->prog->components.count; i++) {
        if (!has_component(mask, i)) continue;
        sb_printf(&b, "%s" STR_FMT, first ? "" : ", ", STR_ARG(g->prog->components.items[i]->name));
        first = false;
    }
    if (first) sb_put(&b, "no components");
    return b.data;
}

// A system's components, singletons, input and devices are passed by pointer,
// and so is what a method's or function's mut parameter changes.
static bool is_pointer_param(const param *p)
{
    if (p->function_param) return p->mode == PARAM_MUT;
    const type_kind k = p->type.kind;
    return k == TY_COMPONENT || k == TY_SINGLETON || k == TY_INPUT || k == TY_RECORD;
}

// What an operator is called in C: add for +, negate for - with one parameter.
static const char *operator_word(const decl *m)
{
    switch (m->op) {
    case T_PLUS: return "add";
    case T_MINUS: return m->params.count == 1 ? "negate" : "subtract";
    case T_STAR: return "multiply";
    case T_SLASH: return "divide";
    case T_PERCENT: return "remainder";
    case T_AMP: return "and";
    case T_PIPE: return "or";
    case T_CARET: return "xor";
    case T_SHL: return "shift_left";
    case T_SHR: return "shift_right";
    case T_EQ: return "equal";
    case T_NE: return "not_equal";
    case T_LT: return "less";
    case T_LE: return "less_equal";
    case T_GT: return "greater";
    case T_GE: return "greater_equal";
    case T_NOT: return "not";
    case T_TILDE: return "complement";
    default: return "operator";
    }
}

// purr_method_Stats_IsDead for Stats.IsDead, purr_function_Combat_Heal for
// Combat.Heal, and purr_operator_Money_add_2 for Money's + (numbered, as a
// struct can have several).
static const char *routine_cname(const decl *m)
{
    sb b = {0};
    if (m->is_operator) {
        int index = 0;
        while (m->owner->methods.items[index] != m) index++;
        sb_printf(&b, "purr_operator_%s_%s_%d", decl_cname(m->owner), operator_word(m), index);
    } else if (m->owner) {
        sb_printf(&b, "purr_method_%s_" STR_FMT, decl_cname(m->owner), STR_ARG(m->name));
    } else {
        sb_printf(&b, "purr_function_%s", decl_cname(m));
    }
    return b.data;
}

static void gen_as(gen *g, sb *o, expr *e, type want);

// A struct's operator applied to `l` and `r` (NULL for one operand).
static void gen_operator_call(gen *g, sb *o, const decl *m, expr *l, expr *r)
{
    sb_printf(o, "%s(", routine_cname(m));
    gen_as(g, o, l, m->params.items[0].type);
    if (r) {
        sb_put(o, ", ");
        gen_as(g, o, r, m->params.items[1].type);
    }
    sb_put(o, ")");
}

// The hidden parameter holding last tick's input, for .pressed and .released.
static const char *prev_input_name(const gen *g, const str name)
{
    sb b = {0};
    sb_printf(&b, "purr_prev_%s", local_cname(g, name));
    return b.data;
}

// ---------------------------------------------------------------------------
// Output helpers

static void line(const gen *g, sb *o, const char *fmt, ...)
{
    for (int i = 0; i < g->indent; i++) sb_put(o, "    ");
    char buf[2048];
    va_list args;
    va_start(args, fmt);
    vsnprintf(buf, sizeof buf, fmt, args);
    va_end(args);
    sb_put(o, buf);
    sb_put(o, "\n");
}

static void indent(const gen *g, sb *o)
{
    for (int i = 0; i < g->indent; i++) sb_put(o, "    ");
}

static void line_directive(gen *g, const loc at)
{
    if (g->opts->line_directives) sb_printf(&g->c, "#line %d \"%s\"\n", at.line, g->paths[at.file]);
}

// Points the following lines back at the generated file itself.
static void line_reset(gen *g)
{
    if (g->opts->line_directives) sb_printf(&g->c, "#line %d \"%s\"\n", g->c.line + 1, g->c_path);
}

// ---------------------------------------------------------------------------
// Expressions

static void gen_expr(gen *g, sb *o, const expr *e);

// Generates `e` into a fresh string. PurrLang expressions have no side effects,
// so an expression that's needed several times (a vector's components) can
// simply be repeated.
static const char *expr_text(gen *g, const expr *e)
{
    sb b = {0};
    gen_expr(g, &b, e);
    return b.data ? b.data : "";
}

// `e` converted to `want`: int -> float, scalars splatted to vectors, int
// vectors widened to float vectors.
static void gen_as(gen *g, sb *o, expr *e, const type want)
{
    const type have = e->type;
    if (e->kind == E_CONDITIONAL && (want.kind != have.kind || want.decl != have.decl)) {
        // Convert each side, so literals stay literals: (c ? 1.0f : 0.0f).
        sb_put(o, "(");
        gen_expr(g, o, e->cond);
        sb_put(o, " ? ");
        gen_as(g, o, e->lhs, want);
        sb_put(o, " : ");
        gen_as(g, o, e->rhs, want);
        sb_put(o, ")");
        return;
    }
    if (want.kind == TY_FLOAT && have.kind == TY_INT) {
        if (e->kind == E_INT) {
            // Same rounding as a runtime conversion, but reads as a plain literal.
            sb_printf(o, "%lld.0f", (long long)e->int_value);
        } else if (e->kind == E_UNARY && e->op == T_MINUS && e->lhs->kind == E_INT && e->lhs->int_value >= 0) {
            sb_printf(o, "-%lld.0f", (long long)e->lhs->int_value);
        } else {
            sb_put(o, "(float)(");
            gen_expr(g, o, e);
            sb_put(o, ")");
        }
        return;
    }
    const int dim = type_dim(want);
    if (dim >= 2 && type_dim(have) == 1) {
        sb_printf(o, "purr_%s_splat(", type_suffix(want));
        gen_as(g, o, e, vector_type(type_is_float_based(want), 1));
        sb_put(o, ")");
        return;
    }
    if (dim >= 2 && type_dim(have) == dim && type_is_float_based(want) && type_is_int_based(have)) {
        sb_printf(o, "purr_%s_from_%s(", type_suffix(want), type_suffix(have));
        gen_expr(g, o, e);
        sb_put(o, ")");
        return;
    }
    gen_expr(g, o, e);
}

// "trs->" for component and singleton parameters, which are pointers; "<expr>." otherwise.
static const char *object_access(gen *g, const expr *obj)
{
    sb b = {0};
    if (obj->kind == E_NAME && obj->bind == BIND_PARAM && is_pointer_param(obj->param)) {
        sb_printf(&b, "%s->", local_cname(g, obj->name));
    } else {
        gen_expr(g, &b, obj);
        sb_put(&b, ".");
    }
    return b.data;
}

// Float literals: always single precision, always with a decimal point.
static void gen_float_literal(sb *o, str text)
{
    if (text.len > 0 && (text.ptr[text.len - 1] == 'f' || text.ptr[text.len - 1] == 'F')) text.len--;
    bool has_point = false;
    for (int i = 0; i < text.len; i++) {
        if (text.ptr[i] == '_') continue; // C has no digit separators.
        sb_putn(o, &text.ptr[i], 1);
        if (text.ptr[i] == '.' || text.ptr[i] == 'e' || text.ptr[i] == 'E') has_point = true;
    }
    sb_put(o, has_point ? "f" : ".0f");
}

// Whether a value of `d` isn't all zeros by default: a field has a default, or
// holds a struct that has one.
static bool has_defaults(const decl *d)
{
    for (int i = 0; i < d->fields.count; i++) {
        const field *f = &d->fields.items[i];
        if (f->default_value || (f->type.kind == TY_STRUCT && has_defaults(f->type.decl))) return true;
    }
    return false;
}

// A value of a component, singleton, input or struct: fields set in `inits`
// (may be NULL) take that value, the rest take their declared default, and
// anything else is zero, padding included.
static void gen_value(gen *g, sb *o, const decl *d, const field_init *inits, const int init_count)
{
    sb_printf(o, "(%s){", type_cname(d));
    int written = 0;
    for (int i = 0; i < d->fields.count; i++) {
        const field *f = &d->fields.items[i];
        expr *value = f->default_value;
        for (int j = 0; j < init_count; j++) {
            if (inits[j].field == f) value = inits[j].value;
        }
        if (!value && f->type.kind == TY_STRUCT && has_defaults(f->type.decl)) {
            sb_printf(o, "%s.%s = ", written++ ? ", " : "", field_cname(f));
            gen_value(g, o, f->type.decl, NULL, 0); // The struct's own defaults
            continue;
        }
        if (!value) continue;
        sb_printf(o, "%s.%s = ", written++ ? ", " : "", field_cname(f));
        gen_as(g, o, value, f->type);
    }
    if (written == 0) sb_put(o, "0");
    sb_put(o, "}");
}

static void gen_literal(gen *g, sb *o, const expr *e)
{
    gen_value(g, o, e->type_decl, e->inits.items, e->inits.count);
}

static void gen_spawn(gen *g, sb *o, const expr *e)
{
    const int a = e->spawn_archetype;
    sb_printf(o, "purr_cmd_spawn%d(purr_w, (purr_spawn%d){", a, a);
    int written = 0;
    for (int i = 0; i < e->args.count; i++) {
        const expr *arg = e->args.items[i];
        // A bare component with no declared defaults is all zeros; leave it out.
        if (arg->kind != E_LITERAL && !has_defaults(arg->type_decl)) continue;
        sb_printf(o, "%s.%s = ", written++ ? ", " : "", type_cname(arg->type_decl));
        gen_value(g, o, arg->type_decl, arg->inits.items, arg->inits.count);
    }
    if (written == 0) sb_put(o, "0");
    sb_put(o, "})");
}

static const char *int_op_helper(const tok_kind op)
{
    switch (op) {
    case T_PLUS: return "purr_add_i";
    case T_MINUS: return "purr_sub_i";
    case T_STAR: return "purr_mul_i";
    case T_SLASH: return "purr_div_i";
    case T_PERCENT: return "purr_mod_i";
    case T_SHL: return "purr_shl_i";
    case T_SHR: return "purr_shr_i";
    default: return NULL; // & | ^ are well defined in C as they are.
    }
}

static const char *c_op(const tok_kind op)
{
    switch (op) {
    case T_PLUS: return "+";
    case T_MINUS: return "-";
    case T_STAR: return "*";
    case T_SLASH: return "/";
    case T_LT: return "<";
    case T_LE: return "<=";
    case T_GT: return ">";
    case T_GE: return ">=";
    case T_EQ: return "==";
    case T_NE: return "!=";
    case T_AND: return "&&";
    case T_OR: return "||";
    case T_AMP: return "&";
    case T_PIPE: return "|";
    case T_CARET: return "^";
    default: return "?";
    }
}

static void gen_binary(gen *g, sb *o, const tok_kind op, expr *l, expr *r, const type result, const decl *overload)
{
    if (overload) {
        gen_operator_call(g, o, overload, l, r);
        return;
    }
    const type lt = l->type;
    const type rt = r->type;
    const type float_t = {TY_FLOAT, NULL};

    // Vectors: component-wise, with both sides converted to the result type.
    if (type_dim(result) >= 2) {
        const char *name = op == T_PLUS ? "add" : op == T_MINUS ? "sub" : op == T_STAR ? "mul" : op == T_SLASH ? "div" : "mod";
        sb_printf(o, "purr_%s_%s(", name, type_suffix(result));
        gen_as(g, o, l, result);
        sb_put(o, ", ");
        gen_as(g, o, r, result);
        sb_put(o, ")");
        return;
    }

    // Matrices: + and - with a matrix, * and / by a number.
    if (matrix_dim(result)) {
        const char *suffix = type_suffix(result);
        if (matrix_dim(lt) && matrix_dim(rt)) {
            sb_printf(o, "purr_%s_%s(", op == T_PLUS ? "add" : "sub", suffix);
            gen_expr(g, o, l);
            sb_put(o, ", ");
            gen_expr(g, o, r);
        } else {
            expr *matrix = matrix_dim(lt) ? l : r;
            expr *scalar = matrix == l ? r : l;
            sb_printf(o, "purr_%s_%s(", op == T_STAR ? "scale" : "divs", suffix);
            gen_expr(g, o, matrix);
            sb_put(o, ", ");
            gen_as(g, o, scalar, float_t);
        }
        sb_put(o, ")");
        return;
    }

    if (lt.kind == TY_ENTITY || lt.kind == TY_PLAYER) {
        const char *fn = lt.kind == TY_ENTITY ? "purr_entity_equal(" : "purr_player_equal(";
        if (op == T_NE) sb_put(o, "!");
        sb_put(o, fn);
        gen_expr(g, o, l);
        sb_put(o, ", ");
        gen_expr(g, o, r);
        sb_put(o, ")");
        return;
    }

    // Integer arithmetic and shifts go through helpers that wrap on overflow and
    // define division by zero and shift counts, so results never depend on the
    // C compiler.
    if (result.kind == TY_INT && int_op_helper(op)) {
        sb_printf(o, "%s(", int_op_helper(op));
        gen_expr(g, o, l);
        sb_put(o, ", ");
        gen_expr(g, o, r);
        sb_put(o, ")");
        return;
    }

    bool mixed = (lt.kind == TY_FLOAT) != (rt.kind == TY_FLOAT) && lt.kind != TY_BOOL;
    sb_put(o, "(");
    if (mixed) gen_as(g, o, l, float_t);
    else gen_expr(g, o, l);
    sb_printf(o, " %s ", c_op(op));
    if (mixed) gen_as(g, o, r, float_t);
    else gen_expr(g, o, r);
    sb_put(o, ")");
}

// float3(...), int(...), quaternion(...), float4x4(...): see check_construct for the forms.
static void gen_construct(gen *g, sb *o, const expr *e)
{
    const type t = e->type;
    const type float_t = {TY_FLOAT, NULL};
    expr *first = e->args.count > 0 ? e->args.items[0] : NULL;

    switch (e->ctor) {
    case CTOR_SCALAR:
        if (t.kind == TY_FLOAT) {
            gen_as(g, o, first, t);
        } else if (first->type.kind == TY_FLOAT) {
            sb_put(o, "purr_i_from_f(");
            gen_expr(g, o, first);
            sb_put(o, ")");
        } else {
            gen_expr(g, o, first);
        }
        break;

    case CTOR_SPLAT:
        sb_printf(o, "purr_%s_splat(", type_suffix(t));
        if (type_is_int_based(t) && first->type.kind == TY_FLOAT) {
            sb_put(o, "purr_i_from_f(");
            gen_expr(g, o, first);
            sb_put(o, ")");
        } else {
            gen_as(g, o, first, vector_type(type_is_float_based(t), 1));
        }
        sb_put(o, ")");
        break;

    case CTOR_CONVERT:
        sb_printf(o, "purr_%s_from_%s(", type_suffix(t), type_suffix(first->type));
        gen_expr(g, o, first);
        sb_put(o, ")");
        break;

    case CTOR_COMPONENTS: {
        if (t.kind == TY_QUATERNION) {
            sb_put(o, "purr_q(");
            for (int i = 0; i < e->args.count; i++) {
                if (i) sb_put(o, ", ");
                gen_as(g, o, e->args.items[i], float_t);
            }
            sb_put(o, ")");
            break;
        }
        const bool is_float = type_is_float_based(t);
        sb_printf(o, "(%s){", c_type(t));
        int written = 0;
        for (int i = 0; i < e->args.count; i++) {
            expr *arg = e->args.items[i];
            const int dim = type_dim(arg->type);
            if (dim == 1) {
                if (written++) sb_put(o, ", ");
                if (is_float) gen_as(g, o, arg, float_t);
                else gen_expr(g, o, arg);
                continue;
            }
            const bool widen = is_float && type_is_int_based(arg->type);
            if (arg->kind == E_MEMBER && arg->swizzle_len > 1) {
                // A swizzle argument: read its components straight from the source vector.
                const char *access = object_access(g, arg->object);
                for (int k = 0; k < dim; k++) {
                    sb_printf(o, "%s%s%s%s", written++ ? ", " : "", widen ? "(float)" : "", access, xyzw[arg->swizzle[k]]);
                }
                continue;
            }
            const char *text = expr_text(g, arg);
            for (int k = 0; k < dim; k++) {
                sb_printf(o, "%s%s(%s).%s", written++ ? ", " : "", widen ? "(float)" : "", text, xyzw[k]);
            }
        }
        sb_put(o, "}");
        break;
    }

    case CTOR_QUAT_FROM_F4:
        sb_put(o, "(purr_quaternion){");
        gen_expr(g, o, first);
        sb_put(o, "}");
        break;

    case CTOR_QUAT_FROM_MAT:
        sb_put(o, "purr_q_from_f3x3(");
        gen_expr(g, o, first);
        sb_put(o, ")");
        break;

    case CTOR_MAT_COLUMNS: {
        const type column = vector_type(true, matrix_dim(t));
        sb_printf(o, "(%s){", c_type(t));
        for (int i = 0; i < e->args.count; i++) {
            if (i) sb_put(o, ", ");
            gen_as(g, o, e->args.items[i], column);
        }
        sb_put(o, "}");
        break;
    }

    case CTOR_MAT_SCALARS: {
        // Arguments are row by row; storage is column by column.
        const int n = matrix_dim(t);
        sb_printf(o, "(%s){", c_type(t));
        for (int col = 0; col < n; col++) {
            sb_put(o, col ? ", {" : "{");
            for (int row = 0; row < n; row++) {
                if (row) sb_put(o, ", ");
                gen_as(g, o, e->args.items[row * n + col], float_t);
            }
            sb_put(o, "}");
        }
        sb_put(o, "}");
        break;
    }

    case CTOR_MAT_FROM_QUAT:
        sb_put(o, "purr_f3x3_from_q(");
        gen_expr(g, o, first);
        sb_put(o, ")");
        break;

    case CTOR_MAT_FROM_ROT_T:
        sb_put(o, "purr_f4x4_from_f3x3_f3(");
        gen_expr(g, o, first);
        sb_put(o, ", ");
        gen_as(g, o, e->args.items[1], (type){TY_FLOAT3, NULL});
        sb_put(o, ")");
        break;

    case CTOR_PLAYER:
        sb_put(o, "purr_player_from_index(");
        gen_expr(g, o, first);
        sb_put(o, ")");
        break;

    case CTOR_COLOR:
        sb_put(o, "(purr_color){");
        for (int i = 0; i < e->args.count; i++) {
            if (i) sb_put(o, ", ");
            gen_as(g, o, e->args.items[i], float_t);
        }
        if (e->args.count == 3) sb_put(o, ", 1.0f");
        sb_put(o, "}");
        break;
    }
}

// "text" as a C string literal. PurrLang's escapes (\" \\ \n) mean the same in
// C; '?' is escaped so no trigraph can form.
static void gen_string(sb *o, const str text)
{
    sb_put(o, "\"");
    for (int i = 0; i < text.len; i++) {
        if (text.ptr[i] == '?') sb_put(o, "\\?");
        else sb_putn(o, &text.ptr[i], 1);
    }
    sb_put(o, "\"");
}

// A call of a method or function. A method gets its value as the first
// argument: a copy, or for a mut method its address. A mut parameter gets the
// caller's variable by address, and the others copies.
static void gen_routine_call(gen *g, sb *o, const expr *e)
{
    const decl *m = e->method;
    sb_printf(o, "%s(", routine_cname(m));
    int args = 0;
    if (m->owner && e->kind == E_CALL) { // IsDead() inside another method: the same value
        const bool have_address = g->routine->is_mut_method;
        sb_put(o, m->is_mut_method ? "purr_self" : have_address ? "*purr_self" : "purr_self");
        args++;
    } else if (m->owner) {
        if (m->is_mut_method) sb_put(o, "&(");
        gen_expr(g, o, e->object);
        if (m->is_mut_method) sb_put(o, ")");
        args++;
    }
    for (int i = 0; i < e->args.count; i++) {
        if (args++) sb_put(o, ", ");
        if (m->params.items[i].mode == PARAM_MUT) {
            sb_put(o, "&(");
            gen_expr(g, o, e->args.items[i]);
            sb_put(o, ")");
        } else {
            gen_as(g, o, e->args.items[i], e->arg_want.items[i]);
        }
    }
    sb_put(o, ")");
}

// input.buttons.jump on last tick's input: purr_prev_input->buttons.jump.
static const char *prev_input_access(gen *g, const expr *field_access)
{
    sb b = {0};
    if (field_access->object->kind == E_NAME) {
        sb_printf(&b, "%s->%s", prev_input_name(g, field_access->object->name), field_cname(field_access->field));
    } else {
        sb_printf(&b, "%s.%s", prev_input_access(g, field_access->object), field_cname(field_access->field));
    }
    return b.data;
}

static void gen_expr(gen *g, sb *o, const expr *e)
{
    switch (e->kind) {
    case E_INT:
        // Hex and binary literals can be negative (0xFFFFFFFF is -1).
        if (e->int_value == INT32_MIN) sb_put(o, "(-2147483647 - 1)");
        else if (e->int_value < 0) sb_printf(o, "(%lld)", (long long)e->int_value);
        else sb_printf(o, "%lld", (long long)e->int_value);
        break;
    case E_FLOAT:
        gen_float_literal(o, e->text);
        break;
    case E_BOOL:
        sb_put(o, e->bool_value ? "true" : "false");
        break;
    case E_STRING:
        gen_string(o, e->text);
        break;
    case E_NAME:
        if (e->bind == BIND_FIELD) {
            // Inside the input's Sample or Sanitize, or a method: a mut method has its value by address.
            const bool by_address = g->routine && g->routine->is_mut_method;
            sb_printf(o, "purr_self%s%s", by_address ? "->" : ".", field_cname(e->field));
        } else if (e->bind == BIND_LOCAL) {
            sb_put(o, local_cname(g, e->name));
        } else if (e->bind == BIND_PARAM && is_pointer_param(e->param)) {
            sb_printf(o, "(*%s)", local_cname(g, e->name));
        } else {
            sb_put(o, local_cname(g, e->name));
        }
        break;
    case E_MEMBER: {
        if (e->c_constant) {
            sb_put(o, e->c_constant); // quaternion.identity, Math.PI
            break;
        }
        if (e->edge != EDGE_NONE) {
            // input.jump.down: this tick's value against last tick's.
            const char *now = expr_text(g, e->object);
            const char *before = prev_input_access(g, e->object);
            if (e->edge == EDGE_DOWN) sb_printf(o, "(%s && !%s)", now, before);
            else sb_printf(o, "(!%s && %s)", now, before);
            break;
        }
        const char *access = object_access(g, e->object);
        if (e->swizzle_len > 1) {
            sb_printf(o, "(%s){", c_type(e->type));
            for (int i = 0; i < e->swizzle_len; i++) sb_printf(o, "%s%s%s", i ? ", " : "", access, xyzw[e->swizzle[i]]);
            sb_put(o, "}");
        } else if (e->swizzle_len == 1) {
            sb_printf(o, "%s%s", access, xyzw[e->swizzle[0]]);
        } else if (e->field) {
            sb_printf(o, "%s%s", access, field_cname(e->field));
        } else {
            sb_printf(o, "%s" STR_FMT, access, STR_ARG(e->member)); // quaternion.value, matrix.c0
        }
        break;
    }
    case E_CALL:
        if (e->call == CALL_METHOD || e->call == CALL_FUNCTION) {
            gen_routine_call(g, o, e);
        } else if (e->call == CALL_CONSTRUCT) {
            gen_construct(g, o, e);
        } else if (e->call == CALL_SPAWN) {
            if (e->hoisted) sb_put(o, e->hoisted); // Already ran, before the statement
            else gen_spawn(g, o, e);
        }
        break;
    case E_LITERAL:
        gen_literal(g, o, e);
        break;
    case E_BINARY:
        gen_binary(g, o, e->op, e->lhs, e->rhs, e->type, e->method);
        break;
    case E_CONDITIONAL:
        // C runs only the chosen side too. Both sides convert to the result type,
        // so they have the same C type.
        sb_put(o, "(");
        gen_expr(g, o, e->cond);
        sb_put(o, " ? ");
        gen_as(g, o, e->lhs, e->type);
        sb_put(o, " : ");
        gen_as(g, o, e->rhs, e->type);
        sb_put(o, ")");
        break;
    case E_UNARY:
        if (e->method) {
            gen_operator_call(g, o, e->method, e->lhs, NULL);
        } else if (e->op == T_NOT || e->op == T_TILDE) {
            sb_put(o, e->op == T_NOT ? "(!" : "(~");
            gen_expr(g, o, e->lhs);
            sb_put(o, ")");
        } else if (type_dim(e->type) >= 2 || matrix_dim(e->type)) {
            sb_printf(o, "purr_neg_%s(", type_suffix(e->type));
            gen_expr(g, o, e->lhs);
            sb_put(o, ")");
        } else if (e->lhs->kind == E_FLOAT || (e->lhs->kind == E_INT && e->lhs->int_value >= 0)) {
            // Negating a non-negative literal can't overflow.
            sb_put(o, "(-");
            gen_expr(g, o, e->lhs);
            sb_put(o, ")");
        } else if (e->type.kind == TY_INT) {
            sb_put(o, "purr_neg_i(");
            gen_expr(g, o, e->lhs);
            sb_put(o, ")");
        } else {
            sb_put(o, "(-");
            gen_expr(g, o, e->lhs);
            sb_put(o, ")");
        }
        break;
    case E_METHOD:
        // Math.Dot(a, b) and friends, and Draw calls, which record into the
        // view's draw list. Entity methods (Add, Remove, Destroy) are
        // statements; see gen_method.
        if (e->call == CALL_METHOD || e->call == CALL_FUNCTION) {
            gen_routine_call(g, o, e);
        } else if (e->call == CALL_BUILTIN || e->call == CALL_DRAW) {
            sb_printf(o, "%s(%s", e->c_callee, e->call == CALL_DRAW ? "purr_draw" : "");
            for (int i = 0; i < e->args.count; i++) {
                if (i || e->call == CALL_DRAW) sb_put(o, ", ");
                gen_as(g, o, e->args.items[i], e->arg_want.items[i]);
            }
            sb_put(o, ")");
        }
        break;
    }
}

// e.Add(...), e.Remove(...), e.Destroy(): the entity expression is evaluated once.
static void gen_method(gen *g, const expr *e)
{
    sb *o = &g->c;
    indent(g, o);
    sb_put(o, "{ purr_entity purr_e = ");
    gen_expr(g, o, e->object);
    sb_put(o, ";");
    for (int i = 0; i < e->args.count && e->call != CALL_DESTROY; i++) {
        const expr *arg = e->args.items[i];
        decl *comp = arg->type_decl;
        if (e->call == CALL_ADD) {
            sb_printf(o, " purr_cmd_add_%s(purr_w, purr_e, ", type_cname(comp));
            gen_value(g, o, comp, arg->inits.items, arg->inits.count);
            sb_put(o, ");");
        } else {
            sb_printf(o, " purr_cmd_remove(purr_w, purr_e, %d);", comp->index);
        }
    }
    if (e->call == CALL_DESTROY) sb_put(o, " purr_cmd_destroy(purr_w, purr_e);");
    sb_put(o, " }\n");
}

// ---------------------------------------------------------------------------
// Statements

// PurrLang evaluates left to right, like C#, but C leaves the order of a call's
// arguments and an initializer's fields unspecified. Spawn is the only
// expression with a side effect (it allocates an entity ID), so each statement's
// spawns run first, into temporaries, in source order: children before the
// expression that uses them, siblings left to right.
typedef VEC(expr *) expr_list;

static void collect_spawns(expr *e, expr_list *out);

static void collect_spawn_list(expr **items, const int count, expr_list *out)
{
    for (int i = 0; i < count; i++) collect_spawns(items[i], out);
}

static void collect_spawns(expr *e, expr_list *out)
{
    if (!e) return;
    switch (e->kind) {
    case E_MEMBER:
        collect_spawns(e->object, out);
        break;
    case E_METHOD:
        collect_spawns(e->object, out);
        collect_spawn_list(e->args.items, e->args.count, out);
        break;
    case E_CALL:
        collect_spawn_list(e->args.items, e->args.count, out);
        if (e->call == CALL_SPAWN) vec_push(*out, e);
        break;
    case E_LITERAL:
        for (int i = 0; i < e->inits.count; i++) collect_spawns(e->inits.items[i].value, out);
        break;
    case E_BINARY:
        collect_spawns(e->lhs, out);
        collect_spawns(e->rhs, out);
        break;
    case E_UNARY:
        collect_spawns(e->lhs, out);
        break;
    case E_CONDITIONAL:
        collect_spawns(e->cond, out); // The checker keeps spawns out of the sides, which may not run
        break;
    default:
        break;
    }
}

// Emits the spawns of a statement's expressions (in the order given) before it.
static void hoist_spawns(gen *g, expr *a, expr *b)
{
    expr_list spawns = {0};
    collect_spawns(a, &spawns);
    collect_spawns(b, &spawns);
    for (int i = 0; i < spawns.count; i++) {
        expr *spawn = spawns.items[i];
        sb name = {0};
        sb_printf(&name, "purr_spawned%d", g->spawn_temps++);
        indent(g, &g->c);
        sb_printf(&g->c, "const purr_entity %s = ", name.data);
        gen_spawn(g, &g->c, spawn);
        sb_put(&g->c, ";\n");
        line(g, &g->c, "(void)%s;", name.data);
        spawn->hoisted = name.data;
    }
}

static void gen_stmt(gen *g, const stmt *s);

// Statements under if/else always get braces.
static void gen_body_stmt(gen *g, const stmt *s)
{
    if (s->kind == S_BLOCK) {
        for (int i = 0; i < s->stmts.count; i++) gen_stmt(g, s->stmts.items[i]);
    } else {
        gen_stmt(g, s);
    }
}

static void gen_stmt(gen *g, const stmt *s)
{
    sb *o = &g->c;
    if (s->kind != S_BLOCK) line_directive(g, s->at);

    switch (s->kind) {
    case S_VAR:
    case S_EXPR: hoist_spawns(g, s->value, NULL); break;
    case S_ASSIGN: hoist_spawns(g, s->target, s->value); break;
    case S_IF: hoist_spawns(g, s->cond, NULL); break;
    default: break;
    }

    switch (s->kind) {
    case S_BLOCK:
        line(g, o, "{");
        g->indent++;
        for (int i = 0; i < s->stmts.count; i++) gen_stmt(g, s->stmts.items[i]);
        g->indent--;
        line(g, o, "}");
        break;

    case S_IF:
        indent(g, o);
        sb_put(o, "if (");
        gen_expr(g, o, s->cond);
        sb_put(o, ") {\n");
        g->indent++;
        gen_body_stmt(g, s->then_stmt);
        g->indent--;
        if (s->else_stmt) {
            line(g, o, "} else {");
            g->indent++;
            gen_body_stmt(g, s->else_stmt);
            g->indent--;
        }
        line(g, o, "}");
        break;

    case S_RETURN:
        if (s->value) {
            indent(g, o);
            sb_put(o, "return ");
            gen_as(g, o, s->value, g->routine->return_type);
            sb_put(o, ";\n");
        } else {
            line(g, o, g->in_input ? "return purr_self;" : "return;");
        }
        break;

    case S_VAR: {
        const char *name = local_cname(g, s->name);
        indent(g, o);
        sb_printf(o, "%s%s %s = ", s->is_mut ? "" : "const ", c_type(s->type), name);
        gen_as(g, o, s->value, s->type);
        sb_printf(o, ";\n");
        line(g, o, "(void)%s;", name);
        break;
    }

    case S_ASSIGN: {
        const expr *target = s->target;
        indent(g, o);
        if (target->kind == E_MEMBER && target->swizzle_len > 1) {
            // v.xz = value: compute into a temporary, then write each component.
            sb_printf(o, "{ const %s purr_t = ", c_type(target->type));
        } else {
            gen_expr(g, o, target);
            sb_put(o, " = ");
        }
        if (s->op == T_ASSIGN) {
            gen_as(g, o, s->value, target->type);
        } else {
            gen_binary(g, o, compound_op(s->op), s->target, s->value, target->type, s->operator_decl);
        }
        sb_put(o, ";");
        if (target->kind == E_MEMBER && target->swizzle_len > 1) {
            const char *access = object_access(g, target->object);
            for (int i = 0; i < target->swizzle_len; i++) {
                sb_printf(o, " %s%s = purr_t.%s;", access, xyzw[target->swizzle[i]], xyzw[i]);
            }
            sb_put(o, " }");
        }
        sb_put(o, "\n");
        break;
    }

    case S_EXPR:
        if (s->value->call == CALL_METHOD || s->value->call == CALL_FUNCTION || s->value->call == CALL_DRAW) {
            indent(g, o);
            gen_expr(g, o, s->value);
            sb_put(o, ";\n");
        } else if (s->value->kind == E_METHOD) {
            gen_method(g, s->value);
        } else {
            indent(g, o);
            sb_put(o, "(void)");
            gen_expr(g, o, s->value);
            sb_put(o, ";\n");
        }
        break;
    }
}

// ---------------------------------------------------------------------------
// Header: types, world layout, public API

// Generated types have no padding the compiler adds: purrc writes it out as
// members, which values always set to zero, so the bytes of a component (and
// of the world) only depend on its fields. Snapshots and state hashes can then
// compare memory directly. Every built-in type is 4-byte aligned with a size
// that's a multiple of 4, except bool.

typedef struct layout {
    int size;
    int align;
} layout;

static layout decl_layout(const decl *d);

static layout type_layout(const type t)
{
    if (t.kind == TY_BOOL) return (layout){1, 1};
    if (t.kind == TY_STRUCT) return decl_layout(t.decl);
    if (type_dim(t) > 0) return (layout){4 * type_dim(t), 4};
    if (matrix_dim(t) > 0) return (layout){4 * matrix_dim(t) * matrix_dim(t), 4};
    switch (t.kind) {
    case TY_QUATERNION: case TY_COLOR: return (layout){16, 4};
    case TY_ENTITY: return (layout){8, 4};
    case TY_PLAYER: return (layout){4, 4};
    default: return (layout){4, 4};
    }
}

static int round_up(const int n, const int align)
{
    return (n + align - 1) / align * align;
}

// The padding before each field of `d` (pad[i] before field i) and after the
// last (pad[count]).
static int *field_padding(const decl *d, layout *out)
{
    int *pad = arena_alloc(sizeof(int) * (size_t)(d->fields.count + 1));
    layout l = {0, 1};
    for (int i = 0; i < d->fields.count; i++) {
        const layout f = type_layout(d->fields.items[i].type);
        pad[i] = round_up(l.size, f.align) - l.size;
        l.size += pad[i] + f.size;
        if (f.align > l.align) l.align = f.align;
    }
    pad[d->fields.count] = round_up(l.size, l.align) - l.size;
    l.size += pad[d->fields.count];
    if (d->fields.count == 0) l.size = 1; // purr_empty
    if (out) *out = l;
    return pad;
}

static layout decl_layout(const decl *d)
{
    layout l;
    field_padding(d, &l);
    return l;
}

static void gen_fields(const gen *g, sb *o, const decl *d)
{
    if (d->fields.count == 0) sb_put(o, "    uint8_t purr_empty; // C structs can't be empty.\n");
    const int *pad = field_padding(d, NULL);
    int pads = 0;
    for (int i = 0; i <= d->fields.count; i++) {
        if (pad[i]) sb_printf(o, "    uint8_t purr_pad%d[%d];\n", pads++, pad[i]);
        if (i == d->fields.count) break;
        const field *f = &d->fields.items[i];
        sb_printf(o, "    %s %s;\n", c_type(f->type), field_cname(f));
    }
    (void)g;
}

// typedef struct Name { fields } Name;, checked to have no hidden padding.
static void gen_type(const gen *g, sb *o, const decl *d)
{
    const char *name = type_cname(d);
    sb_printf(o, "typedef struct %s {\n", name);
    gen_fields(g, o, d);
    sb_printf(o, "} %s;\n", name);
    sb_printf(o, "_Static_assert(sizeof(%s) == %d, \"%s has padding purrc didn't write out\");\n\n", name,
              decl_layout(d).size, name);
}

static void gen_header(gen *g)
{
    const program *prog = g->prog;
    sb *o = &g->h;

    sb_printf(o, "// Generated by purrc from %s. Do not edit.\n", g->from);
    sb_put(o, "#pragma once\n\n");
    sb_put(o, "#include <stdbool.h>\n#include <stdint.h>\n\n");
    sb_put(o, "#include \"purr/color.h\"\n#include \"purr/devices.h\"\n#include \"purr/draw.h\"\n#include \"purr/entity.h\"\n"
              "#include \"purr/math.h\"\n#include \"purr/player.h\"\n\n");
    sb_put(o, "#ifndef PURR_ARCHETYPE_CAPACITY\n#define PURR_ARCHETYPE_CAPACITY 1024u\n#endif\n\n");
    sb_put(o, "#ifndef PURR_MAX_COMMANDS\n#define PURR_MAX_COMMANDS 4096u\n#endif\n\n");

    if (prog->structs.count > 0) sb_put(o, "// Structs, each after the ones it contains\n\n");
    for (int i = 0; i < prog->structs.count; i++) gen_type(g, o, prog->structs.items[i]);

    sb_put(o, "// Components\n\n");
    for (int i = 0; i < prog->components.count; i++) gen_type(g, o, prog->components.items[i]);

    sb_put(o, "// Singletons: one per world\n\n");
    for (int i = 0; i < prog->singletons.count; i++) gen_type(g, o, prog->singletons.items[i]);

    if (prog->input) {
        const char *name = type_cname(prog->input);
        sb_put(o, "// One player's input for one tick\n\n");
        gen_type(g, o, prog->input);
        sb_put(o, "// For hosts that work with any game: whether it has an input, and its type by a fixed name.\n");
        sb_printf(o, "#define PURR_HAS_INPUT 1\ntypedef %s purr_input;\n\n", name);
        sb_put(o, "// The server's slot in purr_world's inputs, after the players'.\n");
        sb_put(o, "#define PURR_SERVER_INPUT PURR_MAX_PLAYERS\n\n");
    }

    sb_put(o, "// Archetypes: storage for each component combination the program can create\n\n");
    for (int a = 0; a < prog->archetypes.count; a++) {
        const uint64_t mask = prog->archetypes.items[a];
        sb_printf(o, "// %s\n", arch_label(g, a));
        sb_printf(o, "typedef struct purr_%s {\n", arch_name(g, a));
        sb_put(o, "    uint32_t count;\n    purr_entity entity[PURR_ARCHETYPE_CAPACITY];\n");
        for (int i = 0; i < prog->components.count; i++) {
            if (!has_component(mask, i)) continue;
            const char *comp = type_cname(prog->components.items[i]);
            sb_printf(o, "    %s %s[PURR_ARCHETYPE_CAPACITY];\n", comp, comp);
        }
        sb_printf(o, "} purr_%s;\n\n", arch_name(g, a));
    }

    sb_put(o, "// Values for each Spawn, per archetype\n\n");
    for (int a = 0; a < prog->archetypes.count; a++) {
        if (!g->prog->spawn_target.items[a]) continue;
        const uint64_t mask = prog->archetypes.items[a];
        sb_printf(o, "typedef struct purr_spawn%d {\n", a);
        if (mask == 0) sb_put(o, "    uint8_t purr_empty;\n");
        for (int i = 0; i < prog->components.count; i++) {
            if (!has_component(mask, i)) continue;
            const char *comp = type_cname(prog->components.items[i]);
            sb_printf(o, "    %s %s;\n", comp, comp);
        }
        sb_printf(o, "} purr_spawn%d;\n\n", a);
    }

    sb_put(o, "// Structural changes, deferred to the end of the tick\n\n");
    sb_put(o, "typedef struct purr_command {\n    uint32_t kind;\n    uint32_t id; // Archetype for spawns, component for add and remove.\n");
    sb_put(o, "    purr_entity entity;\n    union {\n        uint8_t purr_none;\n");
    for (int i = 0; i < prog->components.count; i++) {
        const decl *d = prog->components.items[i];
        if (!has_component(prog->added_mask, d->index)) continue;
        sb_printf(o, "        %s %s;\n", type_cname(d), type_cname(d));
    }
    for (int a = 0; a < prog->archetypes.count; a++) {
        if (g->prog->spawn_target.items[a]) sb_printf(o, "        purr_spawn%d spawn%d;\n", a, a);
    }
    sb_put(o, "    } data;\n} purr_command;\n\n");

    sb_put(o, "// The whole simulation state. Plain data: copying it is a snapshot.\n\n");
    sb_put(o, "typedef struct purr_world {\n");
    for (int i = 0; i < prog->singletons.count; i++) {
        const char *name = type_cname(prog->singletons.items[i]);
        sb_printf(o, "    %s %s;\n", name, name);
    }
    sb_put(o, "    purr_entities entities;\n");
    for (int a = 0; a < prog->archetypes.count; a++) {
        const char *name = arch_name(g, a);
        sb_printf(o, "    purr_%s %s;\n", name, name);
    }
    sb_put(o, "    uint32_t command_count;\n    purr_command commands[PURR_MAX_COMMANDS];\n");
    if (prog->input) {
        const char *name = type_cname(prog->input);
        sb_put(o, "    // Each player's input for this tick and the last, then the server's (PURR_SERVER_INPUT).\n");
        sb_put(o, "    // Last tick's gives .down and .up.\n");
        sb_printf(o, "    %s inputs[PURR_MAX_PLAYERS + 1];\n", name);
        sb_printf(o, "    %s previous_inputs[PURR_MAX_PLAYERS + 1];\n", name);
    }
    sb_put(o, "} purr_world;\n\n");

    sb_put(o, "// Clears the world, sets Time.dt and singleton defaults, runs Main and applies its spawns.\n");
    sb_put(o, "void purr_world_init(purr_world *w, float dt);\n\n");
    sb_put(o, "// Runs every system once, in declaration order, then applies structural changes.\n");
    sb_put(o, "void purr_world_tick(purr_world *w);\n\n");
    sb_put(o, "// Runs every view once, in declaration order, adding their Draw calls to `draw`.\n");
    sb_put(o, "// Call once per frame; reset the list first with purr_draw_reset.\n");
    sb_put(o, "void purr_world_draw(const purr_world *w, purr_draw_list *draw);\n\n");
    sb_put(o, "uint32_t purr_world_entity_count(const purr_world *w);\n\n");
    sb_put(o, "// Prints every entity and its components, for debugging.\n");
    sb_put(o, "void purr_world_print(const purr_world *w);\n\n");
    sb_put(o, "// Component of an entity, or NULL if the entity is dead or doesn't have it.\n");
    for (int i = 0; i < prog->components.count; i++) {
        const char *name = type_cname(prog->components.items[i]);
        sb_printf(o, "%s *purr_get_%s(purr_world *w, purr_entity e);\n", name, name);
    }

    if (prog->input) {
        const char *name = type_cname(prog->input);
        sb_put(o, "\n// Client side: builds the local player's input from the devices by running the\n");
        sb_put(o, "// input's Sample. Call once per tick, then purr_devices_consume(devices).\n");
        sb_printf(o, "%s purr_input_sample(const purr_devices *devices);\n\n", name);
        sb_put(o, "// Sets a player's input for the next tick. A player whose input isn't set keeps\n");
        sb_put(o, "// their last one, which is also the usual guess for a remote player. Inputs set\n");
        sb_put(o, "// here are untrusted: NaN and infinite floats become the field's default, the\n");
        sb_put(o, "// fields' [Clamp], [Min] and [Max] apply, then the input passes through its Sanitize.\n");
        sb_printf(o, "void purr_world_set_input(purr_world *w, purr_player_id player, %s input);\n\n", name);
        sb_put(o, "// Sets the server's input for the next tick. Entities no player owns read it, and\n");
        sb_put(o, "// so do systems that run once per tick. It's kept until set again, like a player's.\n");
        sb_printf(o, "void purr_world_set_server_input(purr_world *w, %s input);\n", name);
    }
}

// ---------------------------------------------------------------------------
// Source: runtime helpers

static void gen_prelude(gen *g)
{
    sb *o = &g->c;
    sb_printf(o, "// Generated by purrc from %s. Do not edit.\n\n", g->from);
    sb_printf(o, "#include \"%s.h\"\n\n", g->opts->name);
    sb_put(o, "#include <stddef.h>\n#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n\n");
    sb_put(o, "// Determinism: never fuse a*b + c, whatever flags this file is built with.\n");
    sb_put(o, "#pragma STDC FP_CONTRACT OFF\n\n");
    sb_put(o, "// Helpers are emitted whether or not this program uses them.\n");
    sb_put(o, "#define PURR_HELPER static inline __attribute__((unused))\n\n");

    sb_put(o,
        "static _Noreturn void purr_fatal(const char *message)\n"
        "{\n"
        "    fprintf(stderr, \"purr: %s\\n\", message);\n"
        "    abort();\n"
        "}\n\n"
        "// Arithmetic on ints, vectors, quaternions and matrices comes from purr/math.h.\n\n");
}

// ---------------------------------------------------------------------------
// Source: archetype storage and structural changes

static void gen_remove_rows(gen *g)
{
    const program *prog = g->prog;
    sb *o = &g->c;
    sb_put(o, "// Swap-remove a row, moving the last entity into the gap.\n\n");
    for (int a = 0; a < prog->archetypes.count; a++) {
        const char *name = arch_name(g, a);
        const uint64_t mask = prog->archetypes.items[a];
        sb_printf(o, "PURR_HELPER void purr_remove_row%d(purr_world *w, uint32_t row)\n{\n", a);
        sb_printf(o, "    purr_%s *a = &w->%s;\n", name, name);
        sb_put(o, "    uint32_t last = --a->count;\n    if (row == last) return;\n");
        sb_put(o, "    a->entity[row] = a->entity[last];\n");
        for (int i = 0; i < prog->components.count; i++) {
            if (!has_component(mask, i)) continue;
            const char *comp = type_cname(prog->components.items[i]);
            sb_printf(o, "    a->%s[row] = a->%s[last];\n", comp, comp);
        }
        sb_printf(o, "    purr_entity_set_location(&w->entities, a->entity[row], (purr_location){%d, row});\n}\n\n", a);
    }
}

static int find_arch(const gen *g, const uint64_t mask)
{
    for (int a = 0; a < g->prog->archetypes.count; a++) {
        if (g->prog->archetypes.items[a] == mask) return a;
    }
    return -1;
}

static void need_move(gen *g, const int from, const int to)
{
    for (int i = 0; i < g->moves.count; i++) {
        if (g->moves.items[i].from == from && g->moves.items[i].to == to) return;
    }
    const transition t = {from, to};
    vec_push(g->moves, t);
}

static void gen_moves(gen *g)
{
    const program *prog = g->prog;
    sb *o = &g->c;

    for (int c = 0; c < prog->components.count; c++) {
        for (int a = 0; a < prog->archetypes.count; a++) {
            const uint64_t mask = prog->archetypes.items[a];
            const uint64_t b = (uint64_t)1 << c;
            if (has_component(prog->added_mask, c) && !(mask & b)) need_move(g, a, find_arch(g, mask | b));
            if (has_component(prog->removed_mask, c) && (mask & b)) need_move(g, a, find_arch(g, mask & ~b));
        }
    }

    sb_put(o, "// Move an entity between archetypes. Returns its row in the new one.\n\n");
    for (int i = 0; i < g->moves.count; i++) {
        const int from = g->moves.items[i].from;
        const int to = g->moves.items[i].to;
        const uint64_t from_mask = prog->archetypes.items[from];
        const uint64_t to_mask = prog->archetypes.items[to];
        sb_printf(o, "// %s -> %s\n", arch_label(g, from), arch_label(g, to));
        sb_printf(o, "PURR_HELPER uint32_t purr_move%d_%d(purr_world *w, uint32_t row)\n{\n", from, to);
        sb_printf(o, "    purr_%s *from = &w->%s;\n", arch_name(g, from), arch_name(g, from));
        sb_printf(o, "    purr_%s *to = &w->%s;\n", arch_name(g, to), arch_name(g, to));
        sb_printf(o, "    if (to->count == PURR_ARCHETYPE_CAPACITY) purr_fatal(\"too many entities with %s (raise PURR_ARCHETYPE_CAPACITY)\");\n",
                  arch_label(g, to));
        sb_put(o, "    uint32_t dst = to->count++;\n    to->entity[dst] = from->entity[row];\n");
        for (int c = 0; c < prog->components.count; c++) {
            if (!has_component(to_mask, c)) continue;
            const char *comp = type_cname(prog->components.items[c]);
            if (has_component(from_mask, c)) sb_printf(o, "    to->%s[dst] = from->%s[row];\n", comp, comp);
            else sb_printf(o, "    to->%s[dst] = (%s){0};\n", comp, comp);
        }
        sb_printf(o, "    purr_entity_set_location(&w->entities, to->entity[dst], (purr_location){%d, dst});\n", to);
        sb_printf(o, "    purr_remove_row%d(w, row);\n    return dst;\n}\n\n", from);
    }
}

static void gen_command_recorders(gen *g)
{
    const program *prog = g->prog;
    sb *o = &g->c;

    sb_put(o, "enum { PURR_CMD_SPAWN, PURR_CMD_ADD, PURR_CMD_REMOVE, PURR_CMD_DESTROY };\n\n");
    sb_put(o,
        "PURR_HELPER purr_command *purr_cmd_push(purr_world *w, uint32_t kind, uint32_t id, purr_entity e)\n"
        "{\n"
        "    if (w->command_count == PURR_MAX_COMMANDS) purr_fatal(\"too many structural changes in one tick (raise PURR_MAX_COMMANDS)\");\n"
        "    purr_command *c = &w->commands[w->command_count++];\n"
        "    c->kind = kind;\n"
        "    c->id = id;\n"
        "    c->entity = e;\n"
        "    return c;\n"
        "}\n\n");

    for (int a = 0; a < prog->archetypes.count; a++) {
        if (!g->prog->spawn_target.items[a]) continue;
        sb_printf(o, "// Spawn: %s\n", arch_label(g, a));
        sb_printf(o, "PURR_HELPER purr_entity purr_cmd_spawn%d(purr_world *w, purr_spawn%d values)\n{\n", a, a);
        sb_put(o, "    purr_entity e = purr_entity_create(&w->entities);\n");
        sb_put(o, "    if (purr_entity_is_null(e)) purr_fatal(\"too many entities (raise PURR_MAX_ENTITIES)\");\n");
        sb_printf(o, "    purr_cmd_push(w, PURR_CMD_SPAWN, %d, e)->data.spawn%d = values;\n    return e;\n}\n\n", a, a);
    }

    for (int c = 0; c < prog->components.count; c++) {
        if (!has_component(prog->added_mask, c)) continue;
        const char *comp = type_cname(prog->components.items[c]);
        sb_printf(o, "PURR_HELPER void purr_cmd_add_%s(purr_world *w, purr_entity e, %s value)\n{\n", comp, comp);
        sb_printf(o, "    purr_cmd_push(w, PURR_CMD_ADD, %d, e)->data.%s = value;\n}\n\n", c, comp);
    }

    sb_put(o,
        "PURR_HELPER void purr_cmd_remove(purr_world *w, purr_entity e, uint32_t component)\n"
        "{\n"
        "    purr_cmd_push(w, PURR_CMD_REMOVE, component, e);\n"
        "}\n\n"
        "PURR_HELPER void purr_cmd_destroy(purr_world *w, purr_entity e)\n"
        "{\n"
        "    purr_cmd_push(w, PURR_CMD_DESTROY, 0, e);\n"
        "}\n\n");
}

static void gen_apply(gen *g)
{
    const program *prog = g->prog;
    sb *o = &g->c;

    // Spawn
    // A program may have no spawns at all, leaving `w` unused.
    sb_put(o, "PURR_HELPER void purr_apply_spawn(purr_world *w, const purr_command *c)\n{\n    (void)w;\n    switch (c->id) {\n");
    for (int a = 0; a < prog->archetypes.count; a++) {
        if (!g->prog->spawn_target.items[a]) continue;
        const uint64_t mask = prog->archetypes.items[a];
        const char *name = arch_name(g, a);
        sb_printf(o, "    case %d: { // %s\n", a, arch_label(g, a));
        sb_printf(o, "        purr_%s *a = &w->%s;\n", name, name);
        sb_printf(o, "        if (a->count == PURR_ARCHETYPE_CAPACITY) purr_fatal(\"too many entities with %s (raise PURR_ARCHETYPE_CAPACITY)\");\n",
                  arch_label(g, a));
        sb_put(o, "        uint32_t row = a->count++;\n        a->entity[row] = c->entity;\n");
        for (int i = 0; i < prog->components.count; i++) {
            if (!has_component(mask, i)) continue;
            const char *comp = type_cname(prog->components.items[i]);
            sb_printf(o, "        a->%s[row] = c->data.spawn%d.%s;\n", comp, a, comp);
        }
        sb_printf(o, "        purr_entity_set_location(&w->entities, c->entity, (purr_location){%d, row});\n", a);
        sb_put(o, "        break;\n    }\n");
    }
    sb_put(o, "    default: break;\n    }\n}\n\n");

    // Add: replace the value if the entity already has the component, otherwise move.
    sb_put(o, "PURR_HELPER void purr_apply_add(purr_world *w, const purr_command *c)\n{\n");
    sb_put(o, "    purr_location loc = purr_entity_location(&w->entities, c->entity);\n");
    sb_put(o, "    if (loc.archetype == PURR_ARCHETYPE_NONE) return; // Destroyed earlier.\n");
    sb_put(o, "    switch (c->id) {\n");
    for (int comp_i = 0; comp_i < prog->components.count; comp_i++) {
        if (!has_component(prog->added_mask, comp_i)) continue;
        const char *comp = type_cname(prog->components.items[comp_i]);
        sb_printf(o, "    case %d: // %s\n        switch (loc.archetype) {\n", comp_i, comp);
        for (int a = 0; a < prog->archetypes.count; a++) {
            const uint64_t mask = prog->archetypes.items[a];
            if (has_component(mask, comp_i)) {
                sb_printf(o, "        case %d: w->%s.%s[loc.row] = c->data.%s; break;\n", a, arch_name(g, a), comp, comp);
            } else {
                const int to = find_arch(g, mask | ((uint64_t)1 << comp_i));
                sb_printf(o, "        case %d: w->%s.%s[purr_move%d_%d(w, loc.row)] = c->data.%s; break;\n",
                          a, arch_name(g, to), comp, a, to, comp);
            }
        }
        sb_put(o, "        default: break;\n        }\n        break;\n");
    }
    sb_put(o, "    default: break;\n    }\n}\n\n");

    // Remove: nothing happens if the entity doesn't have the component.
    sb_put(o, "PURR_HELPER void purr_apply_remove(purr_world *w, const purr_command *c)\n{\n");
    sb_put(o, "    purr_location loc = purr_entity_location(&w->entities, c->entity);\n");
    sb_put(o, "    if (loc.archetype == PURR_ARCHETYPE_NONE) return; // Destroyed earlier.\n");
    sb_put(o, "    switch (c->id) {\n");
    for (int comp_i = 0; comp_i < prog->components.count; comp_i++) {
        if (!has_component(prog->removed_mask, comp_i)) continue;
        sb_printf(o, "    case %d: // %s\n        switch (loc.archetype) {\n", comp_i, type_cname(prog->components.items[comp_i]));
        for (int a = 0; a < prog->archetypes.count; a++) {
            const uint64_t mask = prog->archetypes.items[a];
            if (!has_component(mask, comp_i)) continue;
            const int to = find_arch(g, mask & ~((uint64_t)1 << comp_i));
            sb_printf(o, "        case %d: purr_move%d_%d(w, loc.row); break;\n", a, a, to);
        }
        sb_put(o, "        default: break;\n        }\n        break;\n");
    }
    sb_put(o, "    default: break;\n    }\n}\n\n");

    // Destroy
    sb_put(o, "PURR_HELPER void purr_apply_destroy(purr_world *w, const purr_command *c)\n{\n");
    sb_put(o, "    purr_location loc = purr_entity_location(&w->entities, c->entity);\n");
    sb_put(o, "    switch (loc.archetype) {\n");
    for (int a = 0; a < prog->archetypes.count; a++) {
        sb_printf(o, "    case %d: purr_remove_row%d(w, loc.row); break;\n", a, a);
    }
    sb_put(o, "    default: return; // Already destroyed.\n    }\n");
    sb_put(o, "    purr_entity_destroy(&w->entities, c->entity);\n}\n\n");

    // Commands apply in the order they were recorded, which is deterministic:
    // systems run in a fixed order and iterate entities in a fixed order.
    sb_put(o,
        "static void purr_apply_commands(purr_world *w)\n"
        "{\n"
        "    for (uint32_t i = 0; i < w->command_count; i++) {\n"
        "        const purr_command *c = &w->commands[i];\n"
        "        switch (c->kind) {\n"
        "        case PURR_CMD_SPAWN: purr_apply_spawn(w, c); break;\n"
        "        case PURR_CMD_ADD: purr_apply_add(w, c); break;\n"
        "        case PURR_CMD_REMOVE: purr_apply_remove(w, c); break;\n"
        "        case PURR_CMD_DESTROY: purr_apply_destroy(w, c); break;\n"
        "        default: break;\n"
        "        }\n"
        "    }\n"
        "    w->command_count = 0;\n"
        "}\n\n");

    if (prog->input) {
        const char *name = type_cname(prog->input);
        sb_put(o, "// A player's input, this tick's or last tick's. No player, or an unknown one, means the server's.\n");
        sb_printf(o, "PURR_HELPER const %s *purr_input_of(const purr_world *w, purr_player_id player, bool previous)\n{\n", name);
        sb_put(o, "    int32_t index = purr_player_index(player);\n");
        sb_put(o, "    if (index < 0) index = PURR_SERVER_INPUT;\n");
        sb_put(o, "    return previous ? &w->previous_inputs[index] : &w->inputs[index];\n}\n\n");
    }
}

// ---------------------------------------------------------------------------
// Source: systems

// Systems get the world to record structural changes into. Views get it
// read-only, with the draw list their Draw calls record into.
static void gen_system_body(gen *g, const decl *sys)
{
    sb *o = &g->c;
    sb_printf(o, "// %s " STR_FMT "\n", sys->is_view ? "view" : "system", STR_ARG(sys->qualified));
    // PURR_HELPER: a system that no entity matches is never called.
    if (sys->is_view) {
        sb_printf(o, "PURR_HELPER void purr_view_" STR_FMT "(const purr_world *purr_w, purr_draw_list *purr_draw",
                  STR_ARG(str_from(decl_cname(sys))));
    } else {
        sb_printf(o, "PURR_HELPER void purr_system_" STR_FMT "(purr_world *purr_w", STR_ARG(str_from(decl_cname(sys))));
    }
    for (int i = 0; i < sys->params.count; i++) {
        const param *p = &sys->params.items[i];
        if (p->mode == PARAM_WITH || p->mode == PARAM_WITHOUT) continue;
        const char *name = local_cname(g, p->name);
        if (p->type.kind == TY_ENTITY) {
            sb_printf(o, ", purr_entity %s", name);
        } else {
            sb_printf(o, ", %s%s *restrict %s", p->mode == PARAM_MUT ? "" : "const ", c_type(p->type), name);
        }
        if (p->type.kind == TY_INPUT) {
            sb_printf(o, ", const %s *restrict %s", c_type(p->type), prev_input_name(g, p->name));
        }
    }
    sb_put(o, ")\n{\n");
    g->indent = 1;
    g->spawn_temps = 0;
    line(g, o, "(void)purr_w;");
    if (sys->is_view) line(g, o, "(void)purr_draw;");
    for (int i = 0; i < sys->params.count; i++) {
        const param *p = &sys->params.items[i];
        if (p->name.len > 0) line(g, o, "(void)%s;", local_cname(g, p->name));
        if (p->type.kind == TY_INPUT) line(g, o, "(void)%s;", prev_input_name(g, p->name));
    }
    for (int i = 0; i < sys->body->stmts.count; i++) gen_stmt(g, sys->body->stmts.items[i]);
    g->indent = 0;
    sb_put(o, "}\n");
    line_reset(g);
    sb_put(o, "\n");
}

// Arguments that bind one entity's data to the system's parameters. `mask` is
// the archetype's components; arch_var is NULL for a system that runs once.
static void gen_system_args(gen *g, const decl *sys, const char *arch_var, const uint64_t mask)
{
    sb *o = &g->c;
    for (int i = 0; i < sys->params.count; i++) {
        const param *p = &sys->params.items[i];
        switch (p->type.kind) {
        case TY_ENTITY:
            sb_printf(o, ", %s->entity[purr_i]", arch_var);
            break;
        case TY_SINGLETON:
            sb_printf(o, ", &purr_w->%s", type_cname(p->type.decl));
            break;
        case TY_COMPONENT:
            if (p->mode == PARAM_READ || p->mode == PARAM_MUT) {
                sb_printf(o, ", &%s->%s[purr_i]", arch_var, type_cname(p->type.decl));
            }
            break;
        case TY_INPUT:
            // This tick's input and last tick's: the owner's, or the server's for
            // entities without an Owner and for systems that run once.
            if (arch_var && has_component(mask, g->prog->owner->index)) {
                const char *owner = type_cname(g->prog->owner);
                sb_printf(o, ", purr_input_of(purr_w, %s->%s[purr_i].player, false)", arch_var, owner);
                sb_printf(o, ", purr_input_of(purr_w, %s->%s[purr_i].player, true)", arch_var, owner);
            } else {
                sb_put(o, ", &purr_w->inputs[PURR_SERVER_INPUT], &purr_w->previous_inputs[PURR_SERVER_INPUT]");
            }
            break;
        default:
            break;
        }
    }
}

// The input's Sample, as purr_input_sample: fields start at their defaults
// and the body assigns them from the devices.
// A method's or function's C signature: its value first for a method (by
// address if it's mut), then the parameters, mut ones by address.
static void gen_routine_signature(gen *g, sb *o, const decl *m)
{
    sb_printf(o, "PURR_HELPER %s %s(", m->return_type.kind == TY_VOID ? "void" : c_type(m->return_type), routine_cname(m));
    int n = 0;
    if (m->owner && !m->is_operator) {
        sb_printf(o, m->is_mut_method ? "%s *purr_self" : "const %s purr_self", type_cname(m->owner));
        n++;
    }
    for (int i = 0; i < m->params.count; i++) {
        const param *p = &m->params.items[i];
        sb_printf(o, p->mode == PARAM_MUT ? "%s%s *%s" : "%sconst %s %s", n++ ? ", " : "", c_type(p->type),
                  local_cname(g, p->name));
    }
    if (n == 0) sb_put(o, "void");
    sb_put(o, ")");
}

static void gen_routine(gen *g, const decl *m)
{
    sb *o = &g->c;
    if (m->owner) sb_printf(o, "// " STR_FMT "." STR_FMT "\n", STR_ARG(m->owner->qualified), STR_ARG(m->name));
    else sb_printf(o, "// " STR_FMT "\n", STR_ARG(m->qualified));
    gen_routine_signature(g, o, m);
    sb_put(o, "\n{\n");
    g->indent = 1;
    g->routine = m;
    if (m->owner && !m->is_operator) line(g, o, "(void)purr_self;");
    for (int i = 0; i < m->params.count; i++) line(g, o, "(void)%s;", local_cname(g, m->params.items[i].name));
    for (int i = 0; i < m->body->stmts.count; i++) gen_stmt(g, m->body->stmts.items[i]);
    g->routine = NULL;
    g->indent = 0;
    sb_put(o, "}\n");
    line_reset(g);
    sb_put(o, "\n");
}

// Every method and function, declared first so they can call each other.
static void gen_routines(gen *g)
{
    VEC(const decl *) all = {0};
    for (int i = 0; i < g->prog->decls.count; i++) {
        const decl *d = g->prog->decls.items[i];
        if (d->kind == DECL_FUNCTION) vec_push(all, d);
        for (int k = 0; k < d->methods.count; k++) vec_push(all, d->methods.items[k]);
    }
    if (all.count == 0) return;
    sb *o = &g->c;
    sb_put(o, "// Methods and functions\n\n");
    for (int i = 0; i < all.count; i++) {
        gen_routine_signature(g, o, all.items[i]);
        sb_put(o, ";\n");
    }
    sb_put(o, "\n");
    for (int i = 0; i < all.count; i++) gen_routine(g, all.items[i]);
}

static void gen_sample(gen *g)
{
    const decl *input = g->prog->input;
    sb *o = &g->c;
    const char *name = type_cname(input);
    const char *devices = input->params.count > 0 ? local_cname(g, input->params.items[0].name) : "devices";

    sb_printf(o, "// " STR_FMT "'s Sample\n", STR_ARG(input->name));
    sb_printf(o, "%s purr_input_sample(const purr_devices *restrict %s)\n{\n", name, devices);
    g->indent = 1;
    indent(g, o);
    sb_printf(o, "%s purr_self = ", name);
    gen_value(g, o, input, NULL, 0);
    sb_put(o, ";\n");
    line(g, o, "(void)%s;", devices);
    g->in_input = true;
    if (input->body) {
        for (int i = 0; i < input->body->stmts.count; i++) gen_stmt(g, input->body->stmts.items[i]);
    }
    g->in_input = false;
    line(g, o, "return purr_self;");
    g->indent = 0;
    sb_put(o, "}\n");
    line_reset(g);
    sb_put(o, "\n");
}

// The input's Sanitize, which every input passes through on its way into the
// world (see purr_world_set_input).
static void gen_sanitize(gen *g)
{
    const decl *input = g->prog->input;
    sb *o = &g->c;
    sb_printf(o, "// " STR_FMT "'s Sanitize\n", STR_ARG(input->name));
    sb_printf(o, "static %s purr_input_sanitize(%s purr_self)\n{\n", type_cname(input), type_cname(input));
    g->indent = 1;
    g->in_input = true;
    for (int i = 0; i < input->sanitize->stmts.count; i++) gen_stmt(g, input->sanitize->stmts.items[i]);
    g->in_input = false;
    line(g, o, "return purr_self;");
    g->indent = 0;
    sb_put(o, "}\n");
    line_reset(g);
    sb_put(o, "\n");
}

// Whether a type holds floats, which input from other machines could make NaN
// or infinite.
static bool has_floats(const type t)
{
    switch (t.kind) {
    case TY_FLOAT: case TY_FLOAT2: case TY_FLOAT3: case TY_FLOAT4: case TY_QUATERNION:
    case TY_FLOAT2X2: case TY_FLOAT3X3: case TY_FLOAT4X4: case TY_COLOR:
        return true;
    case TY_STRUCT:
        for (int i = 0; i < t.decl->fields.count; i++) {
            if (has_floats(t.decl->fields.items[i].type)) return true;
        }
        return false;
    default:
        return false;
    }
}

// Whether values of `d` from outside need repairing: floats to check, field
// bounds to apply or padding to clear, in `d` or the structs it holds.
static bool needs_repair(const decl *d)
{
    const int *pad = field_padding(d, NULL);
    for (int i = 0; i <= d->fields.count; i++) {
        if (pad[i]) return true;
    }
    for (int i = 0; i < d->fields.count; i++) {
        const field *f = &d->fields.items[i];
        if (has_floats(f->type) || f->attributes.count > 0) return true;
        if (f->type.kind == TY_STRUCT && needs_repair(f->type.decl)) return true;
    }
    return false;
}

static bool input_needs_repair(const decl *input)
{
    return needs_repair(input);
}

// Replaces each NaN or infinite float of a value with the same float of `def`.
// `in` and `def` are C accesses to values of type `t`.
static void gen_repair_value(gen *g, const char *in, const char *def, const type t)
{
    char a[256];
    char b[256];
    const int columns = matrix_dim(t);
    if (t.kind == TY_FLOAT) {
        line(g, &g->c, "if (!purr_is_finite_f(%s)) %s = %s;", in, in, def);
    } else if (columns > 0) {
        for (int c = 0; c < columns; c++) {
            snprintf(a, sizeof a, "%s.c%d", in, c);
            snprintf(b, sizeof b, "%s.c%d", def, c);
            gen_repair_value(g, a, b, vector_type(true, columns));
        }
    } else if (t.kind == TY_QUATERNION) {
        snprintf(a, sizeof a, "%s.value", in);
        snprintf(b, sizeof b, "%s.value", def);
        gen_repair_value(g, a, b, vector_type(true, 4));
    } else if (t.kind == TY_COLOR) {
        static const char *const channels[] = {"r", "g", "b", "a"};
        for (int i = 0; i < 4; i++) {
            snprintf(a, sizeof a, "%s.%s", in, channels[i]);
            snprintf(b, sizeof b, "%s.%s", def, channels[i]);
            gen_repair_value(g, a, b, (type){TY_FLOAT, NULL});
        }
    } else if (t.kind == TY_STRUCT) {
        for (int i = 0; i < t.decl->fields.count; i++) {
            const field *f = &t.decl->fields.items[i];
            if (!has_floats(f->type)) continue;
            snprintf(a, sizeof a, "%s.%s", in, field_cname(f));
            snprintf(b, sizeof b, "%s.%s", def, field_cname(f));
            gen_repair_value(g, a, b, f->type);
        }
    } else if (has_floats(t)) { // float2 to float4
        for (int i = 0; i < type_dim(t); i++) {
            snprintf(a, sizeof a, "%s.%s", in, xyzw[i]);
            snprintf(b, sizeof b, "%s.%s", def, xyzw[i]);
            gen_repair_value(g, a, b, (type){TY_FLOAT, NULL});
        }
    }
}

// The fields' [Clamp], [Min] and [Max] in `d`, the structs it holds included.
// `in` is the C access to the value, ending in '.'.
static void gen_bounds(gen *g, const decl *d, const char *in)
{
    sb *o = &g->c;
    for (int i = 0; i < d->fields.count; i++) {
        const field *f = &d->fields.items[i];
        for (int k = 0; k < f->attributes.count; k++) {
            const attribute *a = &f->attributes.items[k];
            // [Min(x)] is "at least x": the larger of the two, and [Max] the reverse.
            const char *fn = str_eq_c(a->name, "Clamp") ? "clamp" : str_eq_c(a->name, "Min") ? "max" : "min";
            indent(g, o);
            sb_printf(o, "%s%s = purr_%s_%s(%s%s", in, field_cname(f), fn, type_suffix(f->type), in, field_cname(f));
            for (int v = 0; v < a->values.count; v++) {
                sb_put(o, ", ");
                gen_as(g, o, a->values.items[v], f->type);
            }
            sb_put(o, ");\n");
        }
        if (f->type.kind == TY_STRUCT) {
            char inner[256];
            snprintf(inner, sizeof inner, "%s%s.", in, field_cname(f));
            gen_bounds(g, f->type.decl, inner);
        }
    }
}

// Clears the padding of `d` and the structs it holds: bytes from outside could
// be anything, and the world's bytes must only depend on its fields.
static void gen_clear_padding(gen *g, const decl *d, const char *in)
{
    const int *pad = field_padding(d, NULL);
    int pads = 0;
    for (int i = 0; i <= d->fields.count; i++) {
        if (pad[i]) line(g, &g->c, "memset(%spurr_pad%d, 0, %d);", in, pads++, pad[i]);
        if (i == d->fields.count) break;
        const field *f = &d->fields.items[i];
        if (f->type.kind == TY_STRUCT) {
            char inner[256];
            snprintf(inner, sizeof inner, "%s%s.", in, field_cname(f));
            gen_clear_padding(g, f->type.decl, inner);
        }
    }
}

// Input from other machines is an attack point, so before Sanitize sees it,
// NaN and infinite floats become the field's default (nothing a client sends
// can put them in the simulation), then the fields' [Clamp], [Min] and [Max]
// apply, and padding is cleared.
static void gen_repair(gen *g)
{
    const decl *input = g->prog->input;
    sb *o = &g->c;
    const char *name = type_cname(input);
    sb_printf(o, "// NaN and infinite floats in a " STR_FMT " become the field's default, then the\n", STR_ARG(input->name));
    sb_put(o, "// fields' bounds apply, and padding is cleared.\n");
    sb_printf(o, "static %s purr_input_repair(%s purr_in)\n{\n", name, name);
    g->indent = 1;
    sb_printf(o, "    const %s purr_def = ", name);
    gen_value(g, o, input, NULL, 0);
    sb_put(o, ";\n");
    for (int i = 0; i < input->fields.count; i++) {
        const field *f = &input->fields.items[i];
        if (!has_floats(f->type)) continue;
        char in[256];
        char def[256];
        snprintf(in, sizeof in, "purr_in.%s", field_cname(f));
        snprintf(def, sizeof def, "purr_def.%s", field_cname(f));
        gen_repair_value(g, in, def, f->type);
    }
    gen_bounds(g, input, "purr_in.");
    gen_clear_padding(g, input, "purr_in.");
    line(g, o, "return purr_in;");
    g->indent = 0;
    sb_put(o, "}\n\n");
}

// An input arriving from outside the simulation: repaired, then sanitized.
static void gen_incoming_input(const gen *g, sb *o, const char *value)
{
    const bool repair = input_needs_repair(g->prog->input);
    const bool sanitize = g->prog->input->sanitize != NULL;
    sb_printf(o, "%s%s%s%s%s", sanitize ? "purr_input_sanitize(" : "", repair ? "purr_input_repair(" : "", value,
              repair ? ")" : "", sanitize ? ")" : "");
}

static void gen_system_run(gen *g, const decl *sys)
{
    const program *prog = g->prog;
    sb *o = &g->c;
    const bool view = sys->is_view;
    // How the body is called: its name and the arguments before the parameters.
    sb call = {0};
    sb_printf(&call, "purr_%s_" STR_FMT "(purr_w%s", view ? "view" : "system", STR_ARG(str_from(decl_cname(sys))), view ? ", purr_draw" : "");

    if (view) {
        sb_printf(o, "static void purr_run_view_" STR_FMT "(const purr_world *purr_w, purr_draw_list *purr_draw)\n{\n",
                  STR_ARG(str_from(decl_cname(sys))));
    } else {
        sb_printf(o, "static void purr_run_" STR_FMT "(purr_world *purr_w)\n{\n", STR_ARG(str_from(decl_cname(sys))));
    }

    if (!sys->per_entity) {
        sb_printf(o, "    %s", call.data);
        gen_system_args(g, sys, NULL, 0);
        sb_put(o, ");\n");
    } else {
        bool any = false;
        for (int a = 0; a < prog->archetypes.count; a++) {
            const uint64_t mask = prog->archetypes.items[a];
            if ((mask & sys->need_mask) != sys->need_mask || (mask & sys->without_mask)) continue;
            any = true;
            const char *name = arch_name(g, a);
            sb_printf(o, "    { // %s\n", arch_label(g, a));
            sb_printf(o, "        %spurr_%s *purr_a = &purr_w->%s;\n", view ? "const " : "", name, name);
            sb_put(o, "        for (uint32_t purr_i = 0; purr_i < purr_a->count; purr_i++) {\n");
            sb_printf(o, "            %s", call.data);
            gen_system_args(g, sys, "purr_a", mask);
            sb_put(o, ");\n        }\n    }\n");
        }
        if (!any) {
            sb_printf(o, "    (void)purr_w;%s // No entity matches this %s.\n", view ? " (void)purr_draw;" : "",
                      view ? "view" : "system");
        }
    }
    sb_put(o, "}\n\n");
}

// ---------------------------------------------------------------------------
// Source: public API

static void gen_print_value(sb *o, const type t, const char *access)
{
    char part[300];
    switch (t.kind) {
    case TY_BOOL: sb_printf(o, "        printf(\"%%s\", %s ? \"true\" : \"false\");\n", access); return;
    case TY_INT: sb_printf(o, "        printf(\"%%d\", (int)%s);\n", access); return;
    case TY_FLOAT: sb_printf(o, "        printf(\"%%g\", (double)%s);\n", access); return;
    case TY_ENTITY:
        sb_printf(o, "        printf(\"#%%u.%%u\", (unsigned)%s.index, (unsigned)%s.generation);\n", access, access);
        return;
    case TY_PLAYER:
        sb_printf(o, "        if (purr_player_is_null(%s)) printf(\"no player\"); else printf(\"player %%u\", (unsigned)%s.id - 1u);\n",
                  access, access);
        return;
    case TY_QUATERNION:
        snprintf(part, sizeof part, "%s.value", access);
        gen_print_value(o, (type){TY_FLOAT4, NULL}, part);
        return;
    case TY_COLOR:
        sb_printf(o, "        printf(\"Color(%%g, %%g, %%g, %%g)\", (double)%s.r, (double)%s.g, (double)%s.b, (double)%s.a);\n",
                  access, access, access, access);
        return;
    case TY_STRUCT:
        sb_printf(o, "        printf(\"" STR_FMT " {\");\n", STR_ARG(t.decl->qualified));
        for (int f = 0; f < t.decl->fields.count; f++) {
            const field *fl = &t.decl->fields.items[f];
            sb_printf(o, "        printf(\"%s" STR_FMT " = \");\n", f ? ", " : " ", STR_ARG(fl->name));
            snprintf(part, sizeof part, "%s.%s", access, field_cname(fl));
            gen_print_value(o, fl->type, part);
        }
        sb_put(o, "        printf(\" }\");\n");
        return;
    default:
        break;
    }

    // Vectors as (x, y, z); matrices as [c0 c1 c2], column by column.
    const int dim = type_dim(t);
    const int n = matrix_dim(t);
    if (dim >= 2) {
        sb_put(o, "        printf(\"(\");\n");
        for (int i = 0; i < dim; i++) {
            if (i) sb_put(o, "        printf(\", \");\n");
            snprintf(part, sizeof part, "%s.%s", access, xyzw[i]);
            gen_print_value(o, vector_type(type_is_float_based(t), 1), part);
        }
        sb_put(o, "        printf(\")\");\n");
    } else if (n > 0) {
        sb_put(o, "        printf(\"[\");\n");
        for (int i = 0; i < n; i++) {
            if (i) sb_put(o, "        printf(\" \");\n");
            snprintf(part, sizeof part, "%s.c%d", access, i);
            gen_print_value(o, vector_type(true, n), part);
        }
        sb_put(o, "        printf(\"]\");\n");
    }
}

static void gen_print_fields(sb *o, const decl *d, const char *base)
{
    sb_printf(o, "        printf(\" " STR_FMT " {\");\n", STR_ARG(d->qualified));
    for (int f = 0; f < d->fields.count; f++) {
        const field *fl = &d->fields.items[f];
        sb_printf(o, "        printf(\"%s" STR_FMT " = \");\n", f ? ", " : " ", STR_ARG(fl->name));
        char access[256];
        snprintf(access, sizeof access, "%s.%s", base, field_cname(fl));
        gen_print_value(o, fl->type, access);
    }
    sb_put(o, "        printf(\" }\");\n");
}

static void gen_api(gen *g)
{
    const program *prog = g->prog;
    sb *o = &g->c;

    sb_put(o, "void purr_world_init(purr_world *w, float dt)\n{\n    memset(w, 0, sizeof *w);\n    w->Time.dt = dt;\n");
    for (int i = 0; i < prog->singletons.count; i++) {
        decl *d = prog->singletons.items[i];
        if (!has_defaults(d)) continue;
        sb_printf(o, "    w->%s = ", type_cname(d));
        gen_value(g, o, d, NULL, 0);
        sb_put(o, ";\n");
    }
    if (prog->input) {
        // The defaults go through the same checks as any input, so even before
        // the first input arrives, the simulation sees nothing out of bounds.
        sb_printf(o, "    const %s purr_declared = ", type_cname(prog->input));
        gen_value(g, o, prog->input, NULL, 0);
        sb_printf(o, ";\n    const %s purr_defaults = ", type_cname(prog->input));
        gen_incoming_input(g, o, "purr_declared");
        sb_put(o, ";\n");
        sb_put(o, "    for (uint32_t i = 0; i <= PURR_SERVER_INPUT; i++) {\n");
        sb_put(o, "        w->inputs[i] = purr_defaults;\n        w->previous_inputs[i] = purr_defaults;\n    }\n");
    }
    sb_printf(o, "    purr_system_%s(w", decl_cname(prog->main));
    for (int i = 0; i < prog->main->params.count; i++) {
        sb_printf(o, ", &w->%s", type_cname(prog->main->params.items[i].type.decl));
    }
    sb_put(o, ");\n    purr_apply_commands(w);\n}\n\n");

    sb_put(o, "void purr_world_tick(purr_world *w)\n{\n");
    for (int i = 0; i < prog->systems.count; i++) {
        sb_printf(o, "    purr_run_%s(w);\n", decl_cname(prog->systems.items[i]));
    }
    sb_put(o, "    purr_apply_commands(w);\n");
    if (prog->input) sb_put(o, "    memcpy(w->previous_inputs, w->inputs, sizeof w->inputs);\n");
    sb_put(o, "    w->Time.tick++;\n}\n\n");

    sb_put(o, "void purr_world_draw(const purr_world *w, purr_draw_list *draw)\n{\n");
    for (int i = 0; i < prog->views.count; i++) {
        sb_printf(o, "    purr_run_view_%s(w, draw);\n", decl_cname(prog->views.items[i]));
    }
    if (prog->views.count == 0) sb_put(o, "    (void)w;\n    (void)draw;\n");
    sb_put(o, "}\n\n");

    if (prog->input) {
        sb_printf(o, "void purr_world_set_input(purr_world *w, purr_player_id player, %s input)\n{\n",
                  type_cname(prog->input));
        sb_put(o, "    const int32_t index = purr_player_index(player);\n");
        sb_put(o, "    if (index < 0) return;\n    w->inputs[index] = ");
        gen_incoming_input(g, o, "input");
        sb_put(o, ";\n}\n\n");
        sb_printf(o, "void purr_world_set_server_input(purr_world *w, %s input)\n{\n", type_cname(prog->input));
        sb_put(o, "    w->inputs[PURR_SERVER_INPUT] = ");
        gen_incoming_input(g, o, "input");
        sb_put(o, ";\n}\n\n");
    }

    sb_put(o, "uint32_t purr_world_entity_count(const purr_world *w)\n{\n    uint32_t n = 0;\n");
    for (int a = 0; a < prog->archetypes.count; a++) sb_printf(o, "    n += w->%s.count;\n", arch_name(g, a));
    sb_put(o, "    (void)w;\n    return n;\n}\n\n");

    for (int c = 0; c < prog->components.count; c++) {
        const char *comp = type_cname(prog->components.items[c]);
        sb_printf(o, "%s *purr_get_%s(purr_world *w, purr_entity e)\n{\n", comp, comp);
        sb_put(o, "    purr_location loc = purr_entity_location(&w->entities, e);\n    switch (loc.archetype) {\n");
        for (int a = 0; a < prog->archetypes.count; a++) {
            if (!has_component(prog->archetypes.items[a], c)) continue;
            sb_printf(o, "    case %d: return &w->%s.%s[loc.row];\n", a, arch_name(g, a), comp);
        }
        sb_put(o, "    default: return NULL;\n    }\n}\n\n");
    }

    sb_put(o, "void purr_world_print(const purr_world *w)\n{\n");
    sb_put(o, "    printf(\"tick %d, %u entities\\n\", (int)w->Time.tick, (unsigned)purr_world_entity_count(w));\n");
    for (int s = 0; s < prog->singletons.count; s++) {
        const decl *d = prog->singletons.items[s];
        if (d->builtin) continue;
        char base[256];
        snprintf(base, sizeof base, "w->%s", type_cname(d));
        sb_put(o, "    {\n");
        gen_print_fields(o, d, base);
        sb_put(o, "        printf(\"\\n\");\n    }\n");
    }
    for (int a = 0; a < prog->archetypes.count; a++) {
        const uint64_t mask = prog->archetypes.items[a];
        const char *name = arch_name(g, a);
        sb_printf(o, "    for (uint32_t i = 0; i < w->%s.count; i++) {\n", name);
        sb_printf(o, "        printf(\"  #%%u.%%u\", (unsigned)w->%s.entity[i].index, (unsigned)w->%s.entity[i].generation);\n", name, name);
        for (int c = 0; c < prog->components.count; c++) {
            if (!has_component(mask, c)) continue;
            char base[256];
            snprintf(base, sizeof base, "w->%s.%s[i]", name, type_cname(prog->components.items[c]));
            gen_print_fields(o, prog->components.items[c], base);
        }
        sb_put(o, "        printf(\"\\n\");\n    }\n");
    }
    sb_put(o, "}\n");
}

// ---------------------------------------------------------------------------

static char *forward_slashes(const char *path)
{
    char *out = arena_alloc(strlen(path) + 1);
    for (size_t i = 0; path[i]; i++) out[i] = path[i] == '\\' ? '/' : path[i];
    return out;
}

static bool write_file(const char *path, const sb *b)
{
    FILE *f = fopen(path, "wb");
    if (!f) {
        fprintf(stderr, "purrc: can't write %s\n", path);
        return false;
    }
    const size_t written = fwrite(b->data, 1, b->len, f);
    fclose(f);
    if (written != b->len) {
        fprintf(stderr, "purrc: can't write %s\n", path);
        return false;
    }
    return true;
}

bool codegen(program *prog, const codegen_options *opts)
{
    gen g = {0};
    g.prog = prog;
    g.opts = opts;
    const int files = diag_source_count();
    g.paths = arena_alloc(sizeof(char *) * (size_t)(files > 0 ? files : 1));
    sb from = {0};
    for (int i = 0; i < files; i++) {
        g.paths[i] = forward_slashes(diag_source(i)->path);
        sb_printf(&from, "%s%s", i ? ", " : "", g.paths[i]);
    }
    g.from = from.data ? from.data : "nothing";

    sb path = {0};
    sb_printf(&path, "%s/%s.c", opts->out_dir, opts->name);
    g.c_path = forward_slashes(path.data);

    gen_header(&g);

    gen_prelude(&g);
    gen_remove_rows(&g);
    gen_moves(&g);
    gen_command_recorders(&g);
    gen_apply(&g);
    gen_routines(&g);
    if (prog->input) gen_sample(&g);
    if (prog->input && prog->input->sanitize) gen_sanitize(&g);
    if (prog->input && input_needs_repair(prog->input)) gen_repair(&g);
    gen_system_body(&g, prog->main);
    for (int i = 0; i < prog->systems.count; i++) gen_system_body(&g, prog->systems.items[i]);
    for (int i = 0; i < prog->views.count; i++) gen_system_body(&g, prog->views.items[i]);
    for (int i = 0; i < prog->systems.count; i++) gen_system_run(&g, prog->systems.items[i]);
    for (int i = 0; i < prog->views.count; i++) gen_system_run(&g, prog->views.items[i]);
    gen_api(&g);

    sb h_path = {0};
    sb_printf(&h_path, "%s/%s.h", opts->out_dir, opts->name);
    return write_file(h_path.data, &g.h) && write_file(path.data, &g.c);
}
