# purr_add_game(<target> [SOURCES <file.purr>...] [HOST <file.c>...] [NAME <name>]
#               [TITLE <title>] [STATS] [LAYOUT])
#
# Builds a PurrLang game as the program <target>. The game is every .purr file
# in the current source folder and its subfolders (new ones are picked up by
# the next build), or only the files listed after SOURCES.
#
# Without HOST, the game is the whole program: it opens a window titled TITLE
# (default <target>) and runs (see platform/include/purr/run.h). STATS shows the
# tick, entity count and frame rate in a corner. On the web it's <target>.html.
#
# With HOST, those C files are the program instead, for tests and custom hosts.
# They include the game's generated header, <name>.h (NAME defaults to
# <target>), and drive the game through its API (see AGENTS.md). LAYOUT also
# describes the game's data layout, as purr run does for hot reloading
# (purr_game_layout, see engine/include/purr/layout.h).
#
# The generated files land in the build tree and are regenerated whenever a
# .purr file or purrc changes. Every game is also listed in
# PURR_GAMES_MANIFEST, so editors know which files belong together.

set(PURR_GAMES_MANIFEST "${PROJECT_SOURCE_DIR}/build/tools/games.txt")

function(purr_add_game target)
    cmake_parse_arguments(ARG "STATS;LAYOUT" "NAME;TITLE" "SOURCES;HOST" ${ARGN})
    if("SOURCES" IN_LIST ARG_KEYWORDS_MISSING_VALUES)
        message(FATAL_ERROR "purr_add_game(${target}): list the game's .purr files after SOURCES, or leave "
                            "SOURCES out to use every .purr file in ${CMAKE_CURRENT_SOURCE_DIR} and its subfolders")
    endif()
    set(name "${target}")
    if(ARG_NAME)
        set(name "${ARG_NAME}")
    endif()
    set(title "${target}")
    if(ARG_TITLE)
        set(title "${ARG_TITLE}")
    endif()

    set(sources "")
    if(ARG_SOURCES)
        foreach(file IN LISTS ARG_SOURCES)
            get_filename_component(path "${file}" ABSOLUTE)
            list(APPEND sources "${path}")
        endforeach()
        set(manifest_paths ${sources})
    else()
        # CONFIGURE_DEPENDS: every build checks for new or deleted files first.
        file(GLOB_RECURSE sources CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/*.purr")
        if(NOT sources)
            message(FATAL_ERROR "purr_add_game(${target}): there are no .purr files in ${CMAKE_CURRENT_SOURCE_DIR} "
                                "or its subfolders. Add one, or list the game's files after SOURCES")
        endif()
        # The folder rather than its files, so editors see new files before the next build.
        set(manifest_paths "${CMAKE_CURRENT_SOURCE_DIR}/")
    endif()

    set(layout "")
    if(ARG_LAYOUT)
        set(layout --layout)
    endif()

    set(out_dir "${CMAKE_CURRENT_BINARY_DIR}/purr/${target}")
    set(out_c "${out_dir}/${name}.c")
    set(out_h "${out_dir}/${name}.h")
    add_custom_command(
        OUTPUT "${out_c}" "${out_h}"
        COMMAND "${CMAKE_COMMAND}" -E make_directory "${out_dir}"
        COMMAND ${PURRC_COMMAND} ${sources} -o "${out_dir}" --name "${name}" ${layout}
        DEPENDS ${PURRC_DEPENDS} ${sources}
        COMMENT "purrc ${target}"
        VERBATIM)

    if(ARG_HOST)
        add_executable(${target} ${ARG_HOST} "${out_c}" "${out_h}")
        target_link_libraries(${target} PRIVATE purr)
    else()
        if(NOT TARGET purr_platform)
            message(FATAL_ERROR "purr_add_game(${target}): a game without HOST opens a window, which needs the "
                                "platform layer (PURR_PLATFORM=ON, and platform/ added before this directory)")
        endif()
        set(stats false)
        if(ARG_STATS)
            set(stats true)
        endif()
        set(main "${out_dir}/main.c")
        file(CONFIGURE OUTPUT "${main}" @ONLY CONTENT [[
// Generated by purr_add_game for @target@. Do not edit.
#include "@name@.h"
#include "purr/run.h"

int main(int argc, char **argv)
{
    purr_run(&(purr_run_desc){.title = "@title@", .stats = @stats@, .argc = argc, .argv = argv});
}
]])
        add_executable(${target} "${main}" "${out_c}" "${out_h}")
        target_link_libraries(${target} PRIVATE purr_platform)
        purr_web_page(${target})
    endif()
    target_include_directories(${target} PRIVATE "${out_dir}")

    # `cmake --build --preset <preset> --target <target>_schedule` prints which
    # systems can run at the same time, and why the others wait.
    add_custom_target(${target}_schedule
        COMMAND ${PURRC_COMMAND} ${sources} --schedule --name "${name}"
        DEPENDS ${PURRC_DEPENDS}
        VERBATIM
        USES_TERMINAL)

    foreach(path IN LISTS manifest_paths)
        set_property(GLOBAL APPEND PROPERTY PURR_GAME_LINES "${target}\t${path}")
    endforeach()
    get_property(scheduled GLOBAL PROPERTY PURR_GAMES_MANIFEST_SCHEDULED)
    if(NOT scheduled)
        set_property(GLOBAL PROPERTY PURR_GAMES_MANIFEST_SCHEDULED TRUE)
        cmake_language(DEFER DIRECTORY "${PROJECT_SOURCE_DIR}" CALL purr_write_games_manifest)
    endif()
endfunction()

# Lists every game and its files, one "<game>\t<path>" per line, once all the
# games are known. A path ending in '/' is a folder: every .purr file in it and
# its subfolders. purrls reads it to analyze a game's files together.
function(purr_write_games_manifest)
    get_property(lines GLOBAL PROPERTY PURR_GAME_LINES)
    list(JOIN lines "\n" content)
    file(CONFIGURE OUTPUT "${PURR_GAMES_MANIFEST}" CONTENT "${content}\n" @ONLY)
endfunction()
