#pragma once

#include <stdbool.h>
#include <stdint.h>

#include "tide/net.h"
#include "tide/page.h"

// Entity table: hands out entity handles and records where each entity's data lives.
//
// Temporary implementation written for the Tide v0 transpiler; the project owner
// takes it over later. Code generated by tidec depends on the functions below.
//
// The table lives inside the world, its slots in pages that the world's
// snapshots share (see tide/page.h). It grows as entities are made, with no
// limit but memory, and a zeroed table is an empty one.
//
// One system at a time makes entities, while others may look entities up on
// other threads: like the heap's (see tide/heap.h), the table of pages is read
// as a whole, and when it grows, the old one stays until
// tide_entities_settle, once only one thread runs.

// Slots in each page: 1 << this.
#define TIDE_ENTITY_PAGE_SHIFT 10u

// Archetype of an entity that is alive but whose spawn hasn't been applied yet.
#define TIDE_ARCHETYPE_NONE 0xFFFFFFFFu

// A zeroed handle is the null entity; it is never alive.
typedef struct tide_entity {
    uint32_t index;
    uint32_t generation;
} tide_entity;

typedef struct tide_location {
    uint32_t archetype;
    uint32_t row;
} tide_location;

typedef struct tide_entity_slot {
    uint32_t generation; // Odd while alive, even while free.
    uint32_t archetype;
    uint32_t row;        // While free: the next free slot plus one, or 0
    uint32_t snaps;      // Times it jumped (entity.Snap()): views only blend it between ticks with the same count
} tide_entity_slot;

typedef struct tide_entities {
    uint32_t next_unused; // Slots at or above this were never used.
    uint32_t free_head;   // The last slot freed plus one, or 0: free slots are reused last freed first, so in a deterministic order
    uint32_t pages;       // Pages of slots it has
    uint32_t room;        // Pages `page` has room for
    tide_page **page;     // Before the first, page[-1] holds the table this one replaced, until it's settled
} tide_entities;

tide_entity tide_entity_create(tide_entities *t);

// Returns false if the entity wasn't alive.
bool tide_entity_destroy(tide_entities *t, tide_entity e);

bool tide_entity_alive(const tide_entities *t, tide_entity e);

void tide_entity_set_location(tide_entities *t, tide_entity e, tide_location loc);

// It jumped: views draw it as it is, not blended from the tick before.
void tide_entity_snap(tide_entities *t, tide_entity e);

// Its snap count, or 0 if it isn't alive.
uint32_t tide_entity_snaps(const tide_entities *t, tide_entity e);

// Archetype is TIDE_ARCHETYPE_NONE for dead entities and for pending spawns.
tide_location tide_entity_location(const tide_entities *t, tide_entity e);

// The entity in slot `index` (below next_unused), or the null entity when the
// slot is free.
tide_entity tide_entity_in_slot(const tide_entities *t, uint32_t index);

// For snapshots: `to` becomes `from`, sharing its pages (see tide/page.h).
// The hash covers what's in use, the same for the same entities however the
// table got there.
void tide_entities_copy(tide_entities *to, const tide_entities *from);
uint64_t tide_entities_hash(uint64_t h, const tide_entities *t);

// Lets go of its pages, leaving it empty.
void tide_entities_free(tide_entities *t);

// Frees the tables of pages it grew out of, which code on other threads may
// still have been reading. tide_run_systems calls it once systems are done.
void tide_entities_settle(tide_entities *t);

// The table as bytes, for sending a world and carrying it over: what
// tide_entities_pack writes, and reading it back into an empty table (false
// when the bytes aren't a table).
uint32_t tide_entities_packed_size(const tide_entities *t);
void tide_entities_pack(const tide_entities *t, tide_writer *w);
bool tide_entities_unpack(tide_entities *t, tide_reader *r);

static inline bool tide_entity_is_null(const tide_entity e)
{
    return e.generation == 0;
}

// A generation with this bit is a temporary handle: what Spawn gives in a
// system that splits its entities across threads, until the system is done
// and the entity gets its ID (see tide/jobs.h). Real generations never have it.
#define TIDE_ENTITY_TEMPORARY 0x80000000u

// Whether `e` is temporary: an entity spawned by the system running now, whose
// ID it gets once that system is done. C code given an entity can tell this way.
static inline bool tide_entity_is_temporary(const tide_entity e)
{
    return (e.generation & TIDE_ENTITY_TEMPORARY) != 0;
}

static inline bool tide_entity_equal(const tide_entity a, const tide_entity b)
{
    return a.index == b.index && a.generation == b.generation;
}
