#pragma once

#include <stdbool.h>
#include <stdint.h>

// Entity table: hands out entity handles and records where each entity's data lives.
//
// Temporary implementation written for the Tide v0 transpiler; the project owner
// takes it over later. Code generated by tidec depends on the functions below.
//
// The table lives inside the world: fixed capacity, no pointers, and zero-initialized
// memory is a valid empty table, so snapshots and rollback cover it with a plain copy.

// Must be the same for the engine and generated code; don't override per target.
#ifndef TIDE_MAX_ENTITIES
#define TIDE_MAX_ENTITIES 16384u
#endif

// Archetype of an entity that is alive but whose spawn hasn't been applied yet.
#define TIDE_ARCHETYPE_NONE 0xFFFFFFFFu

// A zeroed handle is the null entity; it is never alive.
typedef struct tide_entity {
    uint32_t index;
    uint32_t generation;
} tide_entity;

typedef struct tide_location {
    uint32_t archetype;
    uint32_t row;
} tide_location;

typedef struct tide_entity_slot {
    uint32_t generation; // Odd while alive, even while free.
    uint32_t archetype;
    uint32_t row;
    uint32_t snaps;      // Times it jumped (entity.Snap()): views only blend it between ticks with the same count
} tide_entity_slot;

typedef struct tide_entities {
    uint32_t next_unused;                       // Slots at or above this were never used.
    uint32_t free_count;
    uint32_t free_list[TIDE_MAX_ENTITIES];      // LIFO, so reuse order is deterministic.
    tide_entity_slot slots[TIDE_MAX_ENTITIES];
} tide_entities;

// Returns the null entity when the table is full.
tide_entity tide_entity_create(tide_entities *t);

// Returns false if the entity wasn't alive.
bool tide_entity_destroy(tide_entities *t, tide_entity e);

bool tide_entity_alive(const tide_entities *t, tide_entity e);

void tide_entity_set_location(tide_entities *t, tide_entity e, tide_location loc);

// It jumped: views draw it as it is, not blended from the tick before.
void tide_entity_snap(tide_entities *t, tide_entity e);

// Its snap count, or 0 if it isn't alive.
uint32_t tide_entity_snaps(const tide_entities *t, tide_entity e);

// Archetype is TIDE_ARCHETYPE_NONE for dead entities and for pending spawns.
tide_location tide_entity_location(const tide_entities *t, tide_entity e);

// For snapshots: copies what's in use, and clears what `to` used beyond it, so
// past the counts a table is all zeros. The hash covers what's in use.
void tide_entities_copy(tide_entities *to, const tide_entities *from);
uint64_t tide_entities_hash(uint64_t h, const tide_entities *t);

static inline bool tide_entity_is_null(const tide_entity e)
{
    return e.generation == 0;
}

static inline bool tide_entity_equal(const tide_entity a, const tide_entity b)
{
    return a.index == b.index && a.generation == b.generation;
}
