#pragma once

#include <stdbool.h>
#include <stdint.h>
#include <string.h>

// Deterministic math for simulation code (see AGENTS.md, Determinism).
//
// Temporary implementation written for Tide by Claude; the project owner
// takes it over later. Code generated by tidec depends on these functions.
//
// Everything in this header is built from IEEE 754 basic operations (+ - * /
// and sqrt) in a fixed order, so results are bit-identical on every supported
// platform. Transcendental functions (sin, exp, ...) live in math.c and follow
// the same rule. Formulas follow Unity.Mathematics.
//
// Names are tide_<function>_<type>, where <type> is one of
// f, f2, f3, f4 (float vectors), i, i2, i3, i4 (int vectors), q (quaternion)
// and f2x2, f3x3, f4x4 (column-major float matrices).

// Never fuse a*b + c, even in files built with other flags.
#pragma STDC FP_CONTRACT OFF

// ---------------------------------------------------------------------------
// Types

typedef struct tide_float2 { float x, y; } tide_float2;
typedef struct tide_float3 { float x, y, z; } tide_float3;
typedef struct tide_float4 { float x, y, z, w; } tide_float4;

typedef struct tide_int2 { int32_t x, y; } tide_int2;
typedef struct tide_int3 { int32_t x, y, z; } tide_int3;
typedef struct tide_int4 { int32_t x, y, z, w; } tide_int4;

// (x, y, z) is the vector part, w the scalar part.
typedef struct tide_quaternion { tide_float4 value; } tide_quaternion;

// Column-major: c0 is the first column.
typedef struct tide_float2x2 { tide_float2 c0, c1; } tide_float2x2;
typedef struct tide_float3x3 { tide_float3 c0, c1, c2; } tide_float3x3;
typedef struct tide_float4x4 { tide_float4 c0, c1, c2, c3; } tide_float4x4;

// Constants. Decimal literals are rounded to float by the compiler.
#define TIDE_PI_F 3.14159265358979323846264338327950f
#define TIDE_TAU_F 6.28318530717958647692528676655900f
#define TIDE_E_F 2.71828182845904523536028747135266f
#define TIDE_DEG2RAD_F 0.01745329251994329576923690768489f
#define TIDE_RAD2DEG_F 57.2957795130823208767981548141052f
#define TIDE_FLT_MIN_NORMAL_F 1.17549435082228750797e-38f

// ---------------------------------------------------------------------------
// Scalars: float

static inline uint32_t tide_f_bits(const float x)
{
    uint32_t u;
    memcpy(&u, &x, sizeof u);
    return u;
}

static inline float tide_f_from_bits(const uint32_t u)
{
    float x;
    memcpy(&x, &u, sizeof x);
    return x;
}

static inline float tide_add_f(const float a, const float b) { return a + b; }
static inline float tide_sub_f(const float a, const float b) { return a - b; }
static inline float tide_mul_f(const float a, const float b) { return a * b; }
static inline float tide_div_f(const float a, const float b) { return a / b; }
static inline float tide_neg_f(const float x) { return -x; }

static inline float tide_abs_f(const float x) { return tide_f_from_bits(tide_f_bits(x) & 0x7FFFFFFFu); }

static inline float tide_copysign_f(const float magnitude, const float sign)
{
    return tide_f_from_bits((tide_f_bits(magnitude) & 0x7FFFFFFFu) | (tide_f_bits(sign) & 0x80000000u));
}

// 1, -1 or 0 (also 0 for NaN).
static inline float tide_sign_f(const float x) { return (x > 0.0f ? 1.0f : 0.0f) - (x < 0.0f ? 1.0f : 0.0f); }

// Every float but NaN and the infinities. Reads the bits, so no compiler
// setting can change the answer.
static inline bool tide_is_finite_f(const float x) { return (tide_f_bits(x) & 0x7F800000u) != 0x7F800000u; }

// With one NaN argument, they return the other one: a bad value, maybe from
// another player's input, shouldn't spread (b != b is true only for NaN).
static inline float tide_min_f(const float a, const float b) { return a < b || b != b ? a : b; }
static inline float tide_max_f(const float a, const float b) { return a > b || b != b ? a : b; }
// NaN gives lo, so a clamped value is always in range (x == x is false only for NaN).
static inline float tide_clamp_f(const float x, const float lo, const float hi)
{
    return x == x ? tide_max_f(lo, tide_min_f(hi, x)) : lo;
}
static inline float tide_saturate_f(const float x) { return tide_clamp_f(x, 0.0f, 1.0f); } // NaN gives 0

// Floats at or above 2^23 in magnitude are already integers (or inf/NaN).
static inline float tide_trunc_f(const float x)
{
    if (!(tide_abs_f(x) < 8388608.0f)) return x;
    return tide_copysign_f((float)(int32_t)x, x);
}

static inline float tide_floor_f(const float x)
{
    const float t = tide_trunc_f(x);
    return t > x ? t - 1.0f : t;
}

static inline float tide_ceil_f(const float x)
{
    const float t = tide_trunc_f(x);
    return t < x ? t + 1.0f : t;
}

// Nearest integer, ties to even: adding and removing 2^23 rounds in the FPU.
static inline float tide_round_f(const float x)
{
    const float a = tide_abs_f(x);
    if (!(a < 8388608.0f)) return x;
    return tide_copysign_f((a + 8388608.0f) - 8388608.0f, x);
}

static inline float tide_frac_f(const float x) { return x - tide_floor_f(x); }

// sqrt is an IEEE basic operation: correctly rounded everywhere.
static inline float tide_sqrt_f(const float x) { return __builtin_sqrtf(x); }

// Exact 1/sqrt, not the approximate rsqrt instruction.
static inline float tide_rsqrt_f(const float x) { return 1.0f / tide_sqrt_f(x); }

static inline float tide_lerp_f(const float a, const float b, const float t) { return a + t * (b - a); }
static inline float tide_unlerp_f(const float a, const float b, const float x) { return (x - a) / (b - a); }
static inline float tide_step_f(const float edge, const float x) { return x >= edge ? 1.0f : 0.0f; }

static inline float tide_smoothstep_f(const float a, const float b, const float x)
{
    const float t = tide_saturate_f((x - a) / (b - a));
    return t * t * (3.0f - (2.0f * t));
}

static inline float tide_radians_f(const float degrees) { return degrees * TIDE_DEG2RAD_F; }
static inline float tide_degrees_f(const float radians) { return radians * TIDE_RAD2DEG_F; }

// Transcendentals, in math.c.
float tide_sin_f(float x);
float tide_cos_f(float x);
float tide_tan_f(float x);
float tide_asin_f(float x);
float tide_acos_f(float x);
float tide_atan_f(float x);
float tide_atan2_f(float y, float x);
float tide_exp_f(float x);
float tide_exp2_f(float x);
float tide_log_f(float x);
float tide_log2_f(float x);
float tide_log10_f(float x);
float tide_pow_f(float x, float y);

// ---------------------------------------------------------------------------
// Scalars: int. Arithmetic wraps on overflow; division and modulo by zero give
// 0; shift counts use their low 5 bits and >> keeps the sign (as in C#).

static inline int32_t tide_add_i(const int32_t a, const int32_t b) { return (int32_t)((uint32_t)a + (uint32_t)b); }
static inline int32_t tide_sub_i(const int32_t a, const int32_t b) { return (int32_t)((uint32_t)a - (uint32_t)b); }
static inline int32_t tide_mul_i(const int32_t a, const int32_t b) { return (int32_t)((uint32_t)a * (uint32_t)b); }
static inline int32_t tide_neg_i(const int32_t a) { return (int32_t)(0u - (uint32_t)a); }
static inline int32_t tide_div_i(const int32_t a, const int32_t b) { return b == 0 ? 0 : b == -1 ? tide_neg_i(a) : a / b; }
static inline int32_t tide_mod_i(const int32_t a, const int32_t b) { return b == 0 || b == -1 ? 0 : a % b; }
static inline int32_t tide_shl_i(const int32_t a, const int32_t n) { return (int32_t)((uint32_t)a << (n & 31)); }
static inline int32_t tide_shr_i(const int32_t a, const int32_t n) { return a < 0 ? ~(~a >> (n & 31)) : a >> (n & 31); }

static inline int32_t tide_abs_i(const int32_t x) { return x < 0 ? tide_neg_i(x) : x; }
static inline int32_t tide_sign_i(const int32_t x) { return (x > 0) - (x < 0); }
static inline int32_t tide_min_i(const int32_t a, const int32_t b) { return a < b ? a : b; }
static inline int32_t tide_max_i(const int32_t a, const int32_t b) { return a > b ? a : b; }
static inline int32_t tide_clamp_i(const int32_t x, const int32_t lo, const int32_t hi) { return tide_max_i(lo, tide_min_i(hi, x)); }

// ---------------------------------------------------------------------------
// Conversions. float -> int truncates toward zero, saturates at the int range
// and maps NaN to 0, so no input is undefined behavior.

static inline float tide_f_from_i(const int32_t x) { return (float)x; }

static inline int32_t tide_i_from_f(const float x)
{
    if (x != x) return 0;
    if (x >= 2147483648.0f) return INT32_MAX;
    if (x <= -2147483648.0f) return INT32_MIN;
    return (int32_t)x;
}

// ---------------------------------------------------------------------------
// Vectors: construction and component-wise operations

static inline tide_float2 tide_f2(const float x, const float y) { return (tide_float2){x, y}; }
static inline tide_float3 tide_f3(const float x, const float y, const float z) { return (tide_float3){x, y, z}; }
static inline tide_float4 tide_f4(const float x, const float y, const float z, const float w) { return (tide_float4){x, y, z, w}; }
static inline tide_int2 tide_i2(const int32_t x, const int32_t y) { return (tide_int2){x, y}; }
static inline tide_int3 tide_i3(const int32_t x, const int32_t y, const int32_t z) { return (tide_int3){x, y, z}; }
static inline tide_int4 tide_i4(const int32_t x, const int32_t y, const int32_t z, const int32_t w) { return (tide_int4){x, y, z, w}; }

static inline tide_float2 tide_f2_splat(const float s) { return (tide_float2){s, s}; }
static inline tide_float3 tide_f3_splat(const float s) { return (tide_float3){s, s, s}; }
static inline tide_float4 tide_f4_splat(const float s) { return (tide_float4){s, s, s, s}; }
static inline tide_int2 tide_i2_splat(const int32_t s) { return (tide_int2){s, s}; }
static inline tide_int3 tide_i3_splat(const int32_t s) { return (tide_int3){s, s, s}; }
static inline tide_int4 tide_i4_splat(const int32_t s) { return (tide_int4){s, s, s, s}; }

// Component-wise versions of a scalar function tide_<name>_f / tide_<name>_i.
#define TIDE_MAP1(V, S, name, f)                                                                  \
    static inline tide_##V##2 tide_##name##_##S##2(const tide_##V##2 a)                            \
    { return (tide_##V##2){tide_##name##_##f(a.x), tide_##name##_##f(a.y)}; }                     \
    static inline tide_##V##3 tide_##name##_##S##3(const tide_##V##3 a)                            \
    { return (tide_##V##3){tide_##name##_##f(a.x), tide_##name##_##f(a.y), tide_##name##_##f(a.z)}; } \
    static inline tide_##V##4 tide_##name##_##S##4(const tide_##V##4 a)                            \
    {                                                                                              \
        return (tide_##V##4){tide_##name##_##f(a.x), tide_##name##_##f(a.y), tide_##name##_##f(a.z), \
                             tide_##name##_##f(a.w)};                                              \
    }

#define TIDE_MAP2(V, S, name, f)                                                                  \
    static inline tide_##V##2 tide_##name##_##S##2(const tide_##V##2 a, const tide_##V##2 b)      \
    { return (tide_##V##2){tide_##name##_##f(a.x, b.x), tide_##name##_##f(a.y, b.y)}; }           \
    static inline tide_##V##3 tide_##name##_##S##3(const tide_##V##3 a, const tide_##V##3 b)      \
    {                                                                                              \
        return (tide_##V##3){tide_##name##_##f(a.x, b.x), tide_##name##_##f(a.y, b.y),             \
                             tide_##name##_##f(a.z, b.z)};                                         \
    }                                                                                              \
    static inline tide_##V##4 tide_##name##_##S##4(const tide_##V##4 a, const tide_##V##4 b)      \
    {                                                                                              \
        return (tide_##V##4){tide_##name##_##f(a.x, b.x), tide_##name##_##f(a.y, b.y),             \
                             tide_##name##_##f(a.z, b.z), tide_##name##_##f(a.w, b.w)};            \
    }

#define TIDE_MAP3(V, S, name, f)                                                                  \
    static inline tide_##V##2 tide_##name##_##S##2(const tide_##V##2 a, const tide_##V##2 b,      \
                                                   const tide_##V##2 c)                            \
    { return (tide_##V##2){tide_##name##_##f(a.x, b.x, c.x), tide_##name##_##f(a.y, b.y, c.y)}; } \
    static inline tide_##V##3 tide_##name##_##S##3(const tide_##V##3 a, const tide_##V##3 b,      \
                                                   const tide_##V##3 c)                            \
    {                                                                                              \
        return (tide_##V##3){tide_##name##_##f(a.x, b.x, c.x), tide_##name##_##f(a.y, b.y, c.y),   \
                             tide_##name##_##f(a.z, b.z, c.z)};                                    \
    }                                                                                              \
    static inline tide_##V##4 tide_##name##_##S##4(const tide_##V##4 a, const tide_##V##4 b,      \
                                                   const tide_##V##4 c)                            \
    {                                                                                              \
        return (tide_##V##4){tide_##name##_##f(a.x, b.x, c.x), tide_##name##_##f(a.y, b.y, c.y),   \
                             tide_##name##_##f(a.z, b.z, c.z), tide_##name##_##f(a.w, b.w, c.w)};  \
    }

// float vectors
TIDE_MAP2(float, f, add, f)
TIDE_MAP2(float, f, sub, f)
TIDE_MAP2(float, f, mul, f)
TIDE_MAP2(float, f, div, f)
TIDE_MAP1(float, f, neg, f)
TIDE_MAP1(float, f, abs, f)
TIDE_MAP1(float, f, sign, f)
TIDE_MAP2(float, f, min, f)
TIDE_MAP2(float, f, max, f)
TIDE_MAP3(float, f, clamp, f)
TIDE_MAP1(float, f, saturate, f)
TIDE_MAP1(float, f, trunc, f)
TIDE_MAP1(float, f, floor, f)
TIDE_MAP1(float, f, ceil, f)
TIDE_MAP1(float, f, round, f)
TIDE_MAP1(float, f, frac, f)
TIDE_MAP1(float, f, sqrt, f)
TIDE_MAP1(float, f, rsqrt, f)
TIDE_MAP3(float, f, lerp, f)
TIDE_MAP3(float, f, unlerp, f)
TIDE_MAP2(float, f, step, f)
TIDE_MAP3(float, f, smoothstep, f)
TIDE_MAP1(float, f, radians, f)
TIDE_MAP1(float, f, degrees, f)
TIDE_MAP1(float, f, sin, f)
TIDE_MAP1(float, f, cos, f)
TIDE_MAP1(float, f, tan, f)
TIDE_MAP1(float, f, asin, f)
TIDE_MAP1(float, f, acos, f)
TIDE_MAP1(float, f, atan, f)
TIDE_MAP2(float, f, atan2, f)
TIDE_MAP1(float, f, exp, f)
TIDE_MAP1(float, f, exp2, f)
TIDE_MAP1(float, f, log, f)
TIDE_MAP1(float, f, log2, f)
TIDE_MAP1(float, f, log10, f)
TIDE_MAP2(float, f, pow, f)

// int vectors
TIDE_MAP2(int, i, add, i)
TIDE_MAP2(int, i, sub, i)
TIDE_MAP2(int, i, mul, i)
TIDE_MAP2(int, i, div, i)
TIDE_MAP2(int, i, mod, i)
TIDE_MAP1(int, i, neg, i)
TIDE_MAP1(int, i, abs, i)
TIDE_MAP1(int, i, sign, i)
TIDE_MAP2(int, i, min, i)
TIDE_MAP2(int, i, max, i)
TIDE_MAP3(int, i, clamp, i)

#undef TIDE_MAP1
#undef TIDE_MAP2
#undef TIDE_MAP3

static inline tide_float2 tide_f2_from_i2(const tide_int2 v) { return (tide_float2){(float)v.x, (float)v.y}; }
static inline tide_float3 tide_f3_from_i3(const tide_int3 v) { return (tide_float3){(float)v.x, (float)v.y, (float)v.z}; }
static inline tide_float4 tide_f4_from_i4(const tide_int4 v) { return (tide_float4){(float)v.x, (float)v.y, (float)v.z, (float)v.w}; }
static inline tide_int2 tide_i2_from_f2(const tide_float2 v) { return (tide_int2){tide_i_from_f(v.x), tide_i_from_f(v.y)}; }
static inline tide_int3 tide_i3_from_f3(const tide_float3 v) { return (tide_int3){tide_i_from_f(v.x), tide_i_from_f(v.y), tide_i_from_f(v.z)}; }
static inline tide_int4 tide_i4_from_f4(const tide_float4 v)
{
    return (tide_int4){tide_i_from_f(v.x), tide_i_from_f(v.y), tide_i_from_f(v.z), tide_i_from_f(v.w)};
}

// ---------------------------------------------------------------------------
// Vectors: geometry

static inline float tide_dot_f2(const tide_float2 a, const tide_float2 b) { return a.x * b.x + a.y * b.y; }
static inline float tide_dot_f3(const tide_float3 a, const tide_float3 b) { return a.x * b.x + a.y * b.y + a.z * b.z; }
static inline float tide_dot_f4(const tide_float4 a, const tide_float4 b) { return a.x * b.x + a.y * b.y + a.z * b.z + a.w * b.w; }

static inline tide_float3 tide_cross_f3(const tide_float3 a, const tide_float3 b)
{
    return (tide_float3){a.y * b.z - a.z * b.y, a.z * b.x - a.x * b.z, a.x * b.y - a.y * b.x};
}

static inline float tide_csum_f2(const tide_float2 v) { return v.x + v.y; }
static inline float tide_csum_f3(const tide_float3 v) { return v.x + v.y + v.z; }
static inline float tide_csum_f4(const tide_float4 v) { return v.x + v.y + v.z + v.w; }
static inline float tide_cmin_f2(const tide_float2 v) { return tide_min_f(v.x, v.y); }
static inline float tide_cmin_f3(const tide_float3 v) { return tide_min_f(tide_min_f(v.x, v.y), v.z); }
static inline float tide_cmin_f4(const tide_float4 v) { return tide_min_f(tide_min_f(v.x, v.y), tide_min_f(v.z, v.w)); }
static inline float tide_cmax_f2(const tide_float2 v) { return tide_max_f(v.x, v.y); }
static inline float tide_cmax_f3(const tide_float3 v) { return tide_max_f(tide_max_f(v.x, v.y), v.z); }
static inline float tide_cmax_f4(const tide_float4 v) { return tide_max_f(tide_max_f(v.x, v.y), tide_max_f(v.z, v.w)); }

// Length, distance, normalize and reflect for each float vector size.
#define TIDE_GEOMETRY(N)                                                                          \
    static inline float tide_lengthsq_f##N(const tide_float##N v) { return tide_dot_f##N(v, v); } \
    static inline float tide_length_f##N(const tide_float##N v) { return tide_sqrt_f(tide_dot_f##N(v, v)); } \
    static inline float tide_distancesq_f##N(const tide_float##N a, const tide_float##N b)       \
    { return tide_lengthsq_f##N(tide_sub_f##N(b, a)); }                                          \
    static inline float tide_distance_f##N(const tide_float##N a, const tide_float##N b)         \
    { return tide_length_f##N(tide_sub_f##N(b, a)); }                                            \
    static inline tide_float##N tide_normalize_f##N(const tide_float##N v)                       \
    { return tide_mul_f##N(tide_f##N##_splat(tide_rsqrt_f(tide_dot_f##N(v, v))), v); }           \
    /* Zero instead of NaN for vectors too short to normalize. */                                \
    static inline tide_float##N tide_normalizesafe_f##N(const tide_float##N v)                   \
    {                                                                                            \
        const float len = tide_dot_f##N(v, v);                                                   \
        return len > TIDE_FLT_MIN_NORMAL_F ? tide_mul_f##N(tide_f##N##_splat(tide_rsqrt_f(len)), v) \
                                           : tide_f##N##_splat(0.0f);                            \
    }                                                                                            \
    static inline tide_float##N tide_reflect_f##N(const tide_float##N i, const tide_float##N n)  \
    {                                                                                            \
        return tide_sub_f##N(i, tide_mul_f##N(tide_mul_f##N(tide_f##N##_splat(2.0f), n),          \
                                              tide_f##N##_splat(tide_dot_f##N(i, n))));          \
    }

TIDE_GEOMETRY(2)
TIDE_GEOMETRY(3)
TIDE_GEOMETRY(4)

#undef TIDE_GEOMETRY

// ---------------------------------------------------------------------------
// Quaternions

static inline tide_quaternion tide_q(const float x, const float y, const float z, const float w)
{
    return (tide_quaternion){{x, y, z, w}};
}

static inline tide_quaternion tide_identity_q(void) { return tide_q(0.0f, 0.0f, 0.0f, 1.0f); }

static inline float tide_dot_q(const tide_quaternion a, const tide_quaternion b) { return tide_dot_f4(a.value, b.value); }

static inline tide_quaternion tide_conjugate_q(const tide_quaternion q)
{
    return tide_q(-q.value.x, -q.value.y, -q.value.z, q.value.w);
}

static inline tide_quaternion tide_inverse_q(const tide_quaternion q)
{
    const float s = 1.0f / tide_dot_f4(q.value, q.value);
    return tide_q(-q.value.x * s, -q.value.y * s, -q.value.z * s, q.value.w * s);
}

static inline tide_quaternion tide_normalize_q(const tide_quaternion q)
{
    return (tide_quaternion){tide_normalize_f4(q.value)};
}

// Identity instead of NaN for quaternions too short to normalize.
static inline tide_quaternion tide_normalizesafe_q(const tide_quaternion q)
{
    const float len = tide_dot_f4(q.value, q.value);
    return len > TIDE_FLT_MIN_NORMAL_F ? (tide_quaternion){tide_mul_f4(tide_f4_splat(tide_rsqrt_f(len)), q.value)}
                                       : tide_identity_q();
}

// Hamilton product: the rotation b followed by a.
static inline tide_quaternion tide_mul_q(const tide_quaternion qa, const tide_quaternion qb)
{
    const tide_float4 a = qa.value;
    const tide_float4 b = qb.value;
    return tide_q(a.w * b.x + a.x * b.w + a.y * b.z - a.z * b.y,
                  a.w * b.y + a.y * b.w + a.z * b.x - a.x * b.z,
                  a.w * b.z + a.z * b.w + a.x * b.y - a.y * b.x,
                  a.w * b.w - a.x * b.x - a.y * b.y - a.z * b.z);
}

static inline tide_float3 tide_rotate_q(const tide_quaternion q, const tide_float3 v)
{
    const tide_float3 u = {q.value.x, q.value.y, q.value.z};
    const tide_float3 t = tide_mul_f3(tide_f3_splat(2.0f), tide_cross_f3(u, v));
    return tide_add_f3(tide_add_f3(v, tide_mul_f3(tide_f3_splat(q.value.w), t)), tide_cross_f3(u, t));
}

static inline tide_float3 tide_forward_q(const tide_quaternion q) { return tide_rotate_q(q, tide_f3(0.0f, 0.0f, 1.0f)); }
static inline tide_float3 tide_up_q(const tide_quaternion q) { return tide_rotate_q(q, tide_f3(0.0f, 1.0f, 0.0f)); }
static inline tide_float3 tide_right_q(const tide_quaternion q) { return tide_rotate_q(q, tide_f3(1.0f, 0.0f, 0.0f)); }

// Rotation of `angle` radians around a normalized axis.
static inline tide_quaternion tide_axisangle_q(const tide_float3 axis, const float angle)
{
    const float s = tide_sin_f(0.5f * angle);
    const float c = tide_cos_f(0.5f * angle);
    return tide_q(axis.x * s, axis.y * s, axis.z * s, c);
}

// Euler angles in radians, applied Z first, then X, then Y (Unity's default order).
static inline tide_quaternion tide_euler_q(const tide_float3 xyz)
{
    const tide_quaternion x = tide_axisangle_q(tide_f3(1.0f, 0.0f, 0.0f), xyz.x);
    const tide_quaternion y = tide_axisangle_q(tide_f3(0.0f, 1.0f, 0.0f), xyz.y);
    const tide_quaternion z = tide_axisangle_q(tide_f3(0.0f, 0.0f, 1.0f), xyz.z);
    return tide_mul_q(tide_mul_q(y, x), z);
}

static inline tide_quaternion tide_nlerp_q(const tide_quaternion a, const tide_quaternion b, const float t)
{
    const tide_float4 bv = tide_dot_q(a, b) < 0.0f ? tide_neg_f4(b.value) : b.value;
    return tide_normalize_q((tide_quaternion){tide_lerp_f4(a.value, bv, tide_f4_splat(t))});
}

static inline tide_quaternion tide_slerp_q(const tide_quaternion a, const tide_quaternion b, const float t)
{
    float dt = tide_dot_q(a, b);
    tide_float4 bv = b.value;
    if (dt < 0.0f) {
        dt = -dt;
        bv = tide_neg_f4(bv);
    }
    if (dt < 0.9995f) {
        const float angle = tide_acos_f(dt);
        const float s = tide_rsqrt_f(1.0f - dt * dt); // 1 / sin(angle)
        const float w1 = tide_sin_f(angle * (1.0f - t)) * s;
        const float w2 = tide_sin_f(angle * t) * s;
        return (tide_quaternion){tide_add_f4(tide_mul_f4(a.value, tide_f4_splat(w1)), tide_mul_f4(bv, tide_f4_splat(w2)))};
    }
    return tide_nlerp_q(a, (tide_quaternion){bv}, t);
}

// Angle in radians between two rotations.
static inline float tide_angle_q(const tide_quaternion a, const tide_quaternion b)
{
    const tide_float4 d = tide_normalize_q(tide_mul_q(tide_conjugate_q(a), b)).value;
    const float half = tide_asin_f(tide_length_f3(tide_f3(d.x, d.y, d.z)));
    return half + half;
}

// ---------------------------------------------------------------------------
// Matrices

static inline tide_float2x2 tide_identity_f2x2(void) { return (tide_float2x2){{1.0f, 0.0f}, {0.0f, 1.0f}}; }

static inline tide_float3x3 tide_identity_f3x3(void)
{
    return (tide_float3x3){{1.0f, 0.0f, 0.0f}, {0.0f, 1.0f, 0.0f}, {0.0f, 0.0f, 1.0f}};
}

static inline tide_float4x4 tide_identity_f4x4(void)
{
    return (tide_float4x4){{1.0f, 0.0f, 0.0f, 0.0f}, {0.0f, 1.0f, 0.0f, 0.0f}, {0.0f, 0.0f, 1.0f, 0.0f}, {0.0f, 0.0f, 0.0f, 1.0f}};
}

// Component-wise matrix operations, column by column.
static inline tide_float2x2 tide_add_f2x2(const tide_float2x2 a, const tide_float2x2 b)
{
    return (tide_float2x2){tide_add_f2(a.c0, b.c0), tide_add_f2(a.c1, b.c1)};
}
static inline tide_float3x3 tide_add_f3x3(const tide_float3x3 a, const tide_float3x3 b)
{
    return (tide_float3x3){tide_add_f3(a.c0, b.c0), tide_add_f3(a.c1, b.c1), tide_add_f3(a.c2, b.c2)};
}
static inline tide_float4x4 tide_add_f4x4(const tide_float4x4 a, const tide_float4x4 b)
{
    return (tide_float4x4){tide_add_f4(a.c0, b.c0), tide_add_f4(a.c1, b.c1), tide_add_f4(a.c2, b.c2), tide_add_f4(a.c3, b.c3)};
}
static inline tide_float2x2 tide_sub_f2x2(const tide_float2x2 a, const tide_float2x2 b)
{
    return (tide_float2x2){tide_sub_f2(a.c0, b.c0), tide_sub_f2(a.c1, b.c1)};
}
static inline tide_float3x3 tide_sub_f3x3(const tide_float3x3 a, const tide_float3x3 b)
{
    return (tide_float3x3){tide_sub_f3(a.c0, b.c0), tide_sub_f3(a.c1, b.c1), tide_sub_f3(a.c2, b.c2)};
}
static inline tide_float4x4 tide_sub_f4x4(const tide_float4x4 a, const tide_float4x4 b)
{
    return (tide_float4x4){tide_sub_f4(a.c0, b.c0), tide_sub_f4(a.c1, b.c1), tide_sub_f4(a.c2, b.c2), tide_sub_f4(a.c3, b.c3)};
}
static inline tide_float2x2 tide_neg_f2x2(const tide_float2x2 a) { return (tide_float2x2){tide_neg_f2(a.c0), tide_neg_f2(a.c1)}; }
static inline tide_float3x3 tide_neg_f3x3(const tide_float3x3 a)
{
    return (tide_float3x3){tide_neg_f3(a.c0), tide_neg_f3(a.c1), tide_neg_f3(a.c2)};
}
static inline tide_float4x4 tide_neg_f4x4(const tide_float4x4 a)
{
    return (tide_float4x4){tide_neg_f4(a.c0), tide_neg_f4(a.c1), tide_neg_f4(a.c2), tide_neg_f4(a.c3)};
}
static inline tide_float2x2 tide_scale_f2x2(const tide_float2x2 a, const float s)
{
    const tide_float2 v = tide_f2_splat(s);
    return (tide_float2x2){tide_mul_f2(a.c0, v), tide_mul_f2(a.c1, v)};
}
static inline tide_float3x3 tide_scale_f3x3(const tide_float3x3 a, const float s)
{
    const tide_float3 v = tide_f3_splat(s);
    return (tide_float3x3){tide_mul_f3(a.c0, v), tide_mul_f3(a.c1, v), tide_mul_f3(a.c2, v)};
}
static inline tide_float4x4 tide_scale_f4x4(const tide_float4x4 a, const float s)
{
    const tide_float4 v = tide_f4_splat(s);
    return (tide_float4x4){tide_mul_f4(a.c0, v), tide_mul_f4(a.c1, v), tide_mul_f4(a.c2, v), tide_mul_f4(a.c3, v)};
}
static inline tide_float2x2 tide_divs_f2x2(const tide_float2x2 a, const float s)
{
    const tide_float2 v = tide_f2_splat(s);
    return (tide_float2x2){tide_div_f2(a.c0, v), tide_div_f2(a.c1, v)};
}
static inline tide_float3x3 tide_divs_f3x3(const tide_float3x3 a, const float s)
{
    const tide_float3 v = tide_f3_splat(s);
    return (tide_float3x3){tide_div_f3(a.c0, v), tide_div_f3(a.c1, v), tide_div_f3(a.c2, v)};
}
static inline tide_float4x4 tide_divs_f4x4(const tide_float4x4 a, const float s)
{
    const tide_float4 v = tide_f4_splat(s);
    return (tide_float4x4){tide_div_f4(a.c0, v), tide_div_f4(a.c1, v), tide_div_f4(a.c2, v), tide_div_f4(a.c3, v)};
}

// Matrix * column vector: the columns weighted by the vector's components.
static inline tide_float2 tide_mul_f2x2_f2(const tide_float2x2 m, const tide_float2 v)
{
    return tide_add_f2(tide_mul_f2(m.c0, tide_f2_splat(v.x)), tide_mul_f2(m.c1, tide_f2_splat(v.y)));
}

static inline tide_float3 tide_mul_f3x3_f3(const tide_float3x3 m, const tide_float3 v)
{
    return tide_add_f3(tide_add_f3(tide_mul_f3(m.c0, tide_f3_splat(v.x)), tide_mul_f3(m.c1, tide_f3_splat(v.y))),
                       tide_mul_f3(m.c2, tide_f3_splat(v.z)));
}

static inline tide_float4 tide_mul_f4x4_f4(const tide_float4x4 m, const tide_float4 v)
{
    return tide_add_f4(tide_add_f4(tide_mul_f4(m.c0, tide_f4_splat(v.x)), tide_mul_f4(m.c1, tide_f4_splat(v.y))),
                       tide_add_f4(tide_mul_f4(m.c2, tide_f4_splat(v.z)), tide_mul_f4(m.c3, tide_f4_splat(v.w))));
}

static inline tide_float2x2 tide_mul_f2x2(const tide_float2x2 a, const tide_float2x2 b)
{
    return (tide_float2x2){tide_mul_f2x2_f2(a, b.c0), tide_mul_f2x2_f2(a, b.c1)};
}

static inline tide_float3x3 tide_mul_f3x3(const tide_float3x3 a, const tide_float3x3 b)
{
    return (tide_float3x3){tide_mul_f3x3_f3(a, b.c0), tide_mul_f3x3_f3(a, b.c1), tide_mul_f3x3_f3(a, b.c2)};
}

static inline tide_float4x4 tide_mul_f4x4(const tide_float4x4 a, const tide_float4x4 b)
{
    return (tide_float4x4){tide_mul_f4x4_f4(a, b.c0), tide_mul_f4x4_f4(a, b.c1), tide_mul_f4x4_f4(a, b.c2),
                           tide_mul_f4x4_f4(a, b.c3)};
}

static inline tide_float2x2 tide_transpose_f2x2(const tide_float2x2 m)
{
    return (tide_float2x2){{m.c0.x, m.c1.x}, {m.c0.y, m.c1.y}};
}

static inline tide_float3x3 tide_transpose_f3x3(const tide_float3x3 m)
{
    return (tide_float3x3){{m.c0.x, m.c1.x, m.c2.x}, {m.c0.y, m.c1.y, m.c2.y}, {m.c0.z, m.c1.z, m.c2.z}};
}

static inline tide_float4x4 tide_transpose_f4x4(const tide_float4x4 m)
{
    return (tide_float4x4){{m.c0.x, m.c1.x, m.c2.x, m.c3.x},
                           {m.c0.y, m.c1.y, m.c2.y, m.c3.y},
                           {m.c0.z, m.c1.z, m.c2.z, m.c3.z},
                           {m.c0.w, m.c1.w, m.c2.w, m.c3.w}};
}

static inline float tide_determinant_f2x2(const tide_float2x2 m) { return m.c0.x * m.c1.y - m.c1.x * m.c0.y; }
static inline float tide_determinant_f3x3(const tide_float3x3 m) { return tide_dot_f3(m.c0, tide_cross_f3(m.c1, m.c2)); }

static inline tide_float2x2 tide_inverse_f2x2(const tide_float2x2 m)
{
    const float s = 1.0f / tide_determinant_f2x2(m);
    return (tide_float2x2){{m.c1.y * s, -m.c0.y * s}, {-m.c1.x * s, m.c0.x * s}};
}

// The inverse's rows are the cross products of pairs of columns, over the determinant.
static inline tide_float3x3 tide_inverse_f3x3(const tide_float3x3 m)
{
    const tide_float3 r0 = tide_cross_f3(m.c1, m.c2);
    const tide_float3 r1 = tide_cross_f3(m.c2, m.c0);
    const tide_float3 r2 = tide_cross_f3(m.c0, m.c1);
    const float s = 1.0f / tide_dot_f3(m.c0, r0);
    return tide_scale_f3x3(tide_transpose_f3x3((tide_float3x3){r0, r1, r2}), s);
}

// 4x4 determinant and inverse by Laplace expansion over 2x2 sub-determinants.
// a<row><col> names below refer to the mathematical matrix, not the storage.
#define TIDE_M4_ELEMENTS(m)                                                                       \
    const float a00 = m.c0.x, a01 = m.c1.x, a02 = m.c2.x, a03 = m.c3.x;                          \
    const float a10 = m.c0.y, a11 = m.c1.y, a12 = m.c2.y, a13 = m.c3.y;                          \
    const float a20 = m.c0.z, a21 = m.c1.z, a22 = m.c2.z, a23 = m.c3.z;                          \
    const float a30 = m.c0.w, a31 = m.c1.w, a32 = m.c2.w, a33 = m.c3.w;                          \
    const float s0 = a00 * a11 - a10 * a01, s1 = a00 * a12 - a10 * a02, s2 = a00 * a13 - a10 * a03; \
    const float s3 = a01 * a12 - a11 * a02, s4 = a01 * a13 - a11 * a03, s5 = a02 * a13 - a12 * a03; \
    const float k5 = a22 * a33 - a32 * a23, k4 = a21 * a33 - a31 * a23, k3 = a21 * a32 - a31 * a22; \
    const float k2 = a20 * a33 - a30 * a23, k1 = a20 * a32 - a30 * a22, k0 = a20 * a31 - a30 * a21;

static inline float tide_determinant_f4x4(const tide_float4x4 m)
{
    TIDE_M4_ELEMENTS(m)
    (void)a02; (void)a03; (void)a12; (void)a13;
    return s0 * k5 - s1 * k4 + s2 * k3 + s3 * k2 - s4 * k1 + s5 * k0;
}

static inline tide_float4x4 tide_inverse_f4x4(const tide_float4x4 m)
{
    TIDE_M4_ELEMENTS(m)
    const float d = 1.0f / (s0 * k5 - s1 * k4 + s2 * k3 + s3 * k2 - s4 * k1 + s5 * k0);
    // b<row><col> of the inverse, stored column by column.
    const float b00 = (a11 * k5 - a12 * k4 + a13 * k3) * d;
    const float b01 = (-a01 * k5 + a02 * k4 - a03 * k3) * d;
    const float b02 = (a31 * s5 - a32 * s4 + a33 * s3) * d;
    const float b03 = (-a21 * s5 + a22 * s4 - a23 * s3) * d;
    const float b10 = (-a10 * k5 + a12 * k2 - a13 * k1) * d;
    const float b11 = (a00 * k5 - a02 * k2 + a03 * k1) * d;
    const float b12 = (-a30 * s5 + a32 * s2 - a33 * s1) * d;
    const float b13 = (a20 * s5 - a22 * s2 + a23 * s1) * d;
    const float b20 = (a10 * k4 - a11 * k2 + a13 * k0) * d;
    const float b21 = (-a00 * k4 + a01 * k2 - a03 * k0) * d;
    const float b22 = (a30 * s4 - a31 * s2 + a33 * s0) * d;
    const float b23 = (-a20 * s4 + a21 * s2 - a23 * s0) * d;
    const float b30 = (-a10 * k3 + a11 * k1 - a12 * k0) * d;
    const float b31 = (a00 * k3 - a01 * k1 + a02 * k0) * d;
    const float b32 = (-a30 * s3 + a31 * s1 - a32 * s0) * d;
    const float b33 = (a20 * s3 - a21 * s1 + a22 * s0) * d;
    return (tide_float4x4){{b00, b10, b20, b30}, {b01, b11, b21, b31}, {b02, b12, b22, b32}, {b03, b13, b23, b33}};
}

#undef TIDE_M4_ELEMENTS

// Rotation matrix of a normalized quaternion.
static inline tide_float3x3 tide_f3x3_from_q(const tide_quaternion q)
{
    const float x = q.value.x, y = q.value.y, z = q.value.z, w = q.value.w;
    const float x2 = x + x, y2 = y + y, z2 = z + z;
    const float xx = x * x2, yy = y * y2, zz = z * z2;
    const float xy = x * y2, xz = x * z2, yz = y * z2;
    const float wx = w * x2, wy = w * y2, wz = w * z2;
    return (tide_float3x3){{1.0f - (yy + zz), xy + wz, xz - wy},
                           {xy - wz, 1.0f - (xx + zz), yz + wx},
                           {xz + wy, yz - wx, 1.0f - (xx + yy)}};
}

// Quaternion of a rotation matrix (Shepperd's method: branch on the largest term).
static inline tide_quaternion tide_q_from_f3x3(const tide_float3x3 m)
{
    const float m00 = m.c0.x, m11 = m.c1.y, m22 = m.c2.z;
    const float trace = m00 + m11 + m22;
    if (trace > 0.0f) {
        const float s = tide_sqrt_f(trace + 1.0f) * 2.0f;
        return tide_q((m.c1.z - m.c2.y) / s, (m.c2.x - m.c0.z) / s, (m.c0.y - m.c1.x) / s, 0.25f * s);
    }
    if (m00 > m11 && m00 > m22) {
        const float s = tide_sqrt_f(1.0f + m00 - m11 - m22) * 2.0f;
        return tide_q(0.25f * s, (m.c1.x + m.c0.y) / s, (m.c2.x + m.c0.z) / s, (m.c1.z - m.c2.y) / s);
    }
    if (m11 > m22) {
        const float s = tide_sqrt_f(1.0f + m11 - m00 - m22) * 2.0f;
        return tide_q((m.c1.x + m.c0.y) / s, 0.25f * s, (m.c2.y + m.c1.z) / s, (m.c2.x - m.c0.z) / s);
    }
    const float s = tide_sqrt_f(1.0f + m22 - m00 - m11) * 2.0f;
    return tide_q((m.c2.x + m.c0.z) / s, (m.c2.y + m.c1.z) / s, 0.25f * s, (m.c0.y - m.c1.x) / s);
}

// Rotation looking along `forward` (normalized) with `up` as a hint.
static inline tide_quaternion tide_lookrotation_q(const tide_float3 forward, const tide_float3 up)
{
    const tide_float3 t = tide_normalize_f3(tide_cross_f3(up, forward));
    return tide_q_from_f3x3((tide_float3x3){t, tide_cross_f3(forward, t), forward});
}

static inline tide_float4x4 tide_f4x4_from_f3x3_f3(const tide_float3x3 rotation, const tide_float3 translation)
{
    return (tide_float4x4){{rotation.c0.x, rotation.c0.y, rotation.c0.z, 0.0f},
                           {rotation.c1.x, rotation.c1.y, rotation.c1.z, 0.0f},
                           {rotation.c2.x, rotation.c2.y, rotation.c2.z, 0.0f},
                           {translation.x, translation.y, translation.z, 1.0f}};
}

static inline tide_float4x4 tide_translate_f4x4(const tide_float3 t)
{
    return tide_f4x4_from_f3x3_f3(tide_identity_f3x3(), t);
}

// Translation, rotation and scale combined: scales, then rotates, then translates.
static inline tide_float4x4 tide_trs_f4x4(const tide_float3 t, const tide_quaternion r, const tide_float3 s)
{
    const tide_float3x3 m = tide_f3x3_from_q(r);
    return tide_f4x4_from_f3x3_f3((tide_float3x3){tide_mul_f3(m.c0, tide_f3_splat(s.x)),
                                                  tide_mul_f3(m.c1, tide_f3_splat(s.y)),
                                                  tide_mul_f3(m.c2, tide_f3_splat(s.z))},
                                  t);
}

// A point (w = 1) through a 4x4 matrix: rotation, scale and translation.
static inline tide_float3 tide_transform_f4x4(const tide_float4x4 m, const tide_float3 p)
{
    const tide_float4 r = tide_mul_f4x4_f4(m, tide_f4(p.x, p.y, p.z, 1.0f));
    return tide_f3(r.x, r.y, r.z);
}

// A direction (w = 0) through a 4x4 matrix: rotation and scale, no translation.
static inline tide_float3 tide_rotate_f4x4(const tide_float4x4 m, const tide_float3 v)
{
    const tide_float4 r = tide_mul_f4x4_f4(m, tide_f4(v.x, v.y, v.z, 0.0f));
    return tide_f3(r.x, r.y, r.z);
}
